import type { Pharmacy, EmergencyRequest, PharmacyEquipment } from "./types";

export interface HospitalWithEquipment extends Pharmacy {
  equipmentList: Omit<PharmacyEquipment, "id" | "pharmacy_id" | "pharmacies">[];
}

export const TOP_INDIA_HOSPITALS: HospitalWithEquipment[] = [
  {
    id: "hosp-delhi-aiims",
    name: "AIIMS New Delhi (All India Institute of Medical Sciences)",
    owner_name: "Dr. M. Srinivas (Director)",
    phone: "011-26588500",
    alt_phone: "011-26588700",
    address: "Sri Aurobindo Marg, Ansari Nagar",
    district: "South Delhi",
    city: "New Delhi",
    state: "Delhi",
    pincode: "110029",
    lat: 28.5672,
    lng: 77.2100,
    pharmacy_type: "urban",
    is_24x7: true,
    open_time: "00:00",
    close_time: "23:59",
    home_delivery: true,
    online_payment: true,
    services: ["Emergency Trauma", "ICU Beds", "Organ Transplant", "Radiotherapy", "Pediatric Care"],
    rating: 4.9,
    verified: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    equipmentList: [
      { equipment_type: "ICU Bed", available_count: 14, total_count: 45, status: "available", condition_note: "Level 3 Trauma ICU", last_verified_at: new Date().toISOString(), updated_at: new Date().toISOString() },
      { equipment_type: "Ventilator", available_count: 8, total_count: 30, status: "available", condition_note: "High-frequency oscillatory", last_verified_at: new Date().toISOString(), updated_at: new Date().toISOString() },
      { equipment_type: "Oxygen Cylinder", available_count: 120, total_count: 200, status: "available", condition_note: "D-Type 7000L Liquid Oxygen", last_verified_at: new Date().toISOString(), updated_at: new Date().toISOString() },
      { equipment_type: "Ambulance", available_count: 6, total_count: 12, status: "available", condition_note: "ALS Cardiac Ambulances", last_verified_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    ]
  },
  {
    id: "hosp-mumbai-lilavati",
    name: "Lilavati Hospital & Research Centre",
    owner_name: "Dr. V. Ravishankar",
    phone: "022-26751000",
    alt_phone: "022-26568000",
    address: "A-791, Bandra Reclamation, Bandra West",
    district: "Mumbai Suburban",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400050",
    lat: 19.0514,
    lng: 72.8286,
    pharmacy_type: "urban",
    is_24x7: true,
    open_time: "00:00",
    close_time: "23:59",
    home_delivery: true,
    online_payment: true,
    services: ["Cardiology", "Neurology", "24x7 Pharmacy", "Blood Bank", "Dialysis"],
    rating: 4.8,
    verified: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    equipmentList: [
      { equipment_type: "ICU Bed", available_count: 9, total_count: 25, status: "available", condition_note: "Cardiac & Neuro ICU", last_verified_at: new Date().toISOString(), updated_at: new Date().toISOString() },
      { equipment_type: "Oxygen Cylinder", available_count: 65, total_count: 100, status: "available", condition_note: "B-Type & D-Type", last_verified_at: new Date().toISOString(), updated_at: new Date().toISOString() },
      { equipment_type: "Dialysis Machine", available_count: 4, total_count: 15, status: "available", condition_note: "Fresenius 4008S", last_verified_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    ]
  },
  {
    id: "hosp-chennai-apollo",
    name: "Apollo Main Hospital Greams Road",
    owner_name: "Dr. Prathap C. Reddy",
    phone: "044-28290200",
    alt_phone: "044-28293333",
    address: "21 Greams Lane, Thousand Lights",
    district: "Chennai",
    city: "Chennai",
    state: "Tamil Nadu",
    pincode: "600006",
    lat: 13.0604,
    lng: 80.2496,
    pharmacy_type: "urban",
    is_24x7: true,
    open_time: "00:00",
    close_time: "23:59",
    home_delivery: true,
    online_payment: true,
    services: ["Proton Therapy", "Cardio-Thoracic", "24x7 Emergency", "Robotic Surgery"],
    rating: 4.9,
    verified: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    equipmentList: [
      { equipment_type: "Ventilator", available_count: 11, total_count: 35, status: "available", condition_note: "EVITA V800", last_verified_at: new Date().toISOString(), updated_at: new Date().toISOString() },
      { equipment_type: "Oxygen Concentrator", available_count: 40, total_count: 80, status: "available", condition_note: "10L Dual Flow", last_verified_at: new Date().toISOString(), updated_at: new Date().toISOString() },
      { equipment_type: "Blood Bag", available_count: 85, total_count: 150, status: "available", condition_note: "O-ve & B+ve Emergency Stock", last_verified_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    ]
  },
  {
    id: "hosp-bengaluru-manipal",
    name: "Manipal Hospital HAL Old Airport Road",
    owner_name: "Dr. Manish Rai",
    phone: "080-25024444",
    alt_phone: "080-25023333",
    address: "98 HAL Old Airport Rd, Kodihalli",
    district: "Bengaluru Urban",
    city: "Bengaluru",
    state: "Karnataka",
    pincode: "560017",
    lat: 12.9585,
    lng: 77.6484,
    pharmacy_type: "urban",
    is_24x7: true,
    open_time: "00:00",
    close_time: "23:59",
    home_delivery: true,
    online_payment: true,
    services: ["Oncology", "Organ Transplant", "Pediatric ICU", "24x7 Ambulance"],
    rating: 4.8,
    verified: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    equipmentList: [
      { equipment_type: "ICU Bed", available_count: 7, total_count: 30, status: "available", condition_note: "Surgical ICU", last_verified_at: new Date().toISOString(), updated_at: new Date().toISOString() },
      { equipment_type: "Ambulance", available_count: 5, total_count: 10, status: "available", condition_note: "Ventilator Equipped Ambulance", last_verified_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    ]
  },
  {
    id: "hosp-hyderabad-yashoda",
    name: "Yashoda Hospitals Secunderabad",
    owner_name: "Dr. G. S. Rao",
    phone: "040-45674567",
    alt_phone: "040-27713333",
    address: "Alexander Road, Secunderabad",
    district: "Hyderabad",
    city: "Hyderabad",
    state: "Telangana",
    pincode: "500003",
    lat: 17.4399,
    lng: 78.4983,
    pharmacy_type: "urban",
    is_24x7: true,
    open_time: "00:00",
    close_time: "23:59",
    home_delivery: true,
    online_payment: true,
    services: ["Neuro Care", "Critical Care", "Accident & Emergency", "ECMO"],
    rating: 4.7,
    verified: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    equipmentList: [
      { equipment_type: "ECG Machine", available_count: 15, total_count: 20, status: "available", condition_note: "12-Lead Portable", last_verified_at: new Date().toISOString(), updated_at: new Date().toISOString() },
      { equipment_type: "Oxygen Cylinder", available_count: 90, total_count: 140, status: "available", condition_note: "High Pressure Medical Oxygen", last_verified_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    ]
  },
  {
    id: "hosp-kolkata-amri",
    name: "AMRI Hospitals Salt Lake",
    owner_name: "Dr. Rupak Barua",
    phone: "033-66800000",
    alt_phone: "033-23350000",
    address: "JC-16 & 17, Sector III, Salt Lake City",
    district: "North 24 Parganas",
    city: "Kolkata",
    state: "West Bengal",
    pincode: "700098",
    lat: 22.5697,
    lng: 88.4127,
    pharmacy_type: "urban",
    is_24x7: true,
    open_time: "00:00",
    close_time: "23:59",
    home_delivery: true,
    online_payment: true,
    services: ["Nephrology", "Cardiac Care", "Pulmonology", "Neonatal ICU"],
    rating: 4.6,
    verified: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    equipmentList: [
      { equipment_type: "Nebulizer", available_count: 25, total_count: 30, status: "available", condition_note: "Ultrasonic Mesh Nebulizers", last_verified_at: new Date().toISOString(), updated_at: new Date().toISOString() },
      { equipment_type: "ICU Bed", available_count: 6, total_count: 20, status: "available", condition_note: "COVID & General Isolation", last_verified_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    ]
  },
  {
    id: "hosp-lucknow-medanta",
    name: "Medanta Hospital Lucknow",
    owner_name: "Dr. Naresh Trehan",
    phone: "0522-4505050",
    alt_phone: "0522-4505000",
    address: "Sector A, Pocket 1, Sushant Golf City, Amar Shaheed Path",
    district: "Lucknow",
    city: "Lucknow",
    state: "Uttar Pradesh",
    pincode: "226030",
    lat: 26.7820,
    lng: 80.9985,
    pharmacy_type: "semi-urban",
    is_24x7: true,
    open_time: "00:00",
    close_time: "23:59",
    home_delivery: true,
    online_payment: true,
    services: ["Heart Institute", "Bone & Joint", "Liver Transplant", "Trauma Center"],
    rating: 4.8,
    verified: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    equipmentList: [
      { equipment_type: "Ventilator", available_count: 12, total_count: 28, status: "available", condition_note: "Servo-u Advanced", last_verified_at: new Date().toISOString(), updated_at: new Date().toISOString() },
      { equipment_type: "Oxygen Cylinder", available_count: 110, total_count: 180, status: "available", condition_note: "Jumbo D-Type", last_verified_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    ]
  },
  {
    id: "hosp-jaipur-sms",
    name: "Sawai Man Singh (SMS) Hospital Jaipur",
    owner_name: "Dr. Achal Sharma",
    phone: "0141-2560291",
    alt_phone: "0141-2518200",
    address: "Jawaharlal Nehru Marg, Ashok Nagar",
    district: "Jaipur",
    city: "Jaipur",
    state: "Rajasthan",
    pincode: "302004",
    lat: 26.9023,
    lng: 75.8152,
    pharmacy_type: "urban",
    is_24x7: true,
    open_time: "00:00",
    close_time: "23:59",
    home_delivery: false,
    online_payment: true,
    services: ["Government Medical Care", "Emergency Trauma", "Free Generic Medicines", "ICU Services"],
    rating: 4.7,
    verified: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    equipmentList: [
      { equipment_type: "ICU Bed", available_count: 18, total_count: 60, status: "available", condition_note: "State Trauma Center ICU", last_verified_at: new Date().toISOString(), updated_at: new Date().toISOString() },
      { equipment_type: "Ambulance", available_count: 8, total_count: 20, status: "available", condition_note: "108 Emergency Fleet", last_verified_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    ]
  },
  {
    id: "hosp-ahmedabad-sterling",
    name: "Sterling Hospitals Ahmedabad",
    owner_name: "Dr. Simmardeep Singh",
    phone: "079-40011111",
    alt_phone: "079-40011000",
    address: "Sterling Hospital Road, Memnagar",
    district: "Ahmedabad",
    city: "Ahmedabad",
    state: "Gujarat",
    pincode: "380052",
    lat: 23.0487,
    lng: 72.5332,
    pharmacy_type: "urban",
    is_24x7: true,
    open_time: "00:00",
    close_time: "23:59",
    home_delivery: true,
    online_payment: true,
    services: ["Stroke Center", "Cardiology", "Burn Unit", "Comprehensive Cancer Care"],
    rating: 4.8,
    verified: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    equipmentList: [
      { equipment_type: "Defibrillator", available_count: 8, total_count: 12, status: "available", condition_note: "Biphasic Defib with Pacing", last_verified_at: new Date().toISOString(), updated_at: new Date().toISOString() },
      { equipment_type: "Oxygen Cylinder", available_count: 80, total_count: 120, status: "available", condition_note: "Liquid Oxygen & Cylinders", last_verified_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    ]
  },
  {
    id: "hosp-patna-aiims",
    name: "AIIMS Patna (All India Institute of Medical Sciences)",
    owner_name: "Dr. Gopal Krushna Pal",
    phone: "0612-2451070",
    alt_phone: "0612-2451000",
    address: "Phulwari Sharif, Khagaul Road",
    district: "Patna",
    city: "Patna",
    state: "Bihar",
    pincode: "801507",
    lat: 25.5601,
    lng: 85.0456,
    pharmacy_type: "semi-urban",
    is_24x7: true,
    open_time: "00:00",
    close_time: "23:59",
    home_delivery: false,
    online_payment: true,
    services: ["Tertiary Healthcare", "High Risk Maternity", "Dialysis Unit", "Emergency Care"],
    rating: 4.7,
    verified: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    equipmentList: [
      { equipment_type: "ICU Bed", available_count: 10, total_count: 30, status: "available", condition_note: "Medical & Pediatric ICU", last_verified_at: new Date().toISOString(), updated_at: new Date().toISOString() },
      { equipment_type: "Oxygen Concentrator", available_count: 35, total_count: 60, status: "available", condition_note: "High Pressure Oxygen Units", last_verified_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    ]
  },
  {
    id: "hosp-kochi-aster",
    name: "Aster Medcity Kochi",
    owner_name: "Dr. Harish Pillai",
    phone: "0484-6699999",
    alt_phone: "0484-2800000",
    address: "Kuttisahib Road, Cheranalloor",
    district: "Ernakulam",
    city: "Kochi",
    state: "Kerala",
    pincode: "682027",
    lat: 10.0465,
    lng: 76.2694,
    pharmacy_type: "urban",
    is_24x7: true,
    open_time: "00:00",
    close_time: "23:59",
    home_delivery: true,
    online_payment: true,
    services: ["Quaternary Care", "Robot Assisted Surgery", "Bone Marrow Transplant", "ECMO Center"],
    rating: 4.9,
    verified: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    equipmentList: [
      { equipment_type: "Ventilator", available_count: 14, total_count: 40, status: "available", condition_note: "Dräger Evita V500", last_verified_at: new Date().toISOString(), updated_at: new Date().toISOString() },
      { equipment_type: "Ambulance", available_count: 4, total_count: 8, status: "available", condition_note: "Neonatal & Adult Transport", last_verified_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    ]
  },
  {
    id: "hosp-rural-udumalpet-phc",
    name: "Primary Health Centre (PHC) Udumalpet",
    owner_name: "Dr. K. Arunkumar",
    phone: "04252-224100",
    alt_phone: "04252-224101",
    address: "Palani Road, Near Bus Stand",
    district: "Tiruppur",
    city: "Udumalpet",
    state: "Tamil Nadu",
    pincode: "642126",
    lat: 10.5847,
    lng: 77.2475,
    pharmacy_type: "rural",
    is_24x7: true,
    open_time: "00:00",
    close_time: "23:59",
    home_delivery: false,
    online_payment: true,
    services: ["Maternal & Child Health", "ASHA Worker Dispatch", "Snakebite Anti-venom", "First Aid Triage"],
    rating: 4.6,
    verified: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    equipmentList: [
      { equipment_type: "Oxygen Cylinder", available_count: 15, total_count: 20, status: "available", condition_note: "Emergency B-Type Bottles", last_verified_at: new Date().toISOString(), updated_at: new Date().toISOString() },
      { equipment_type: "Nebulizer", available_count: 8, total_count: 10, status: "available", condition_note: "Asthma Relief Nebulizer", last_verified_at: new Date().toISOString(), updated_at: new Date().toISOString() },
      { equipment_type: "Ambulance", available_count: 2, total_count: 3, status: "available", condition_note: "108 Rural Dispatch", last_verified_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    ]
  }
];

export const TOP_INDIA_EMERGENCY_REQUESTS: EmergencyRequest[] = [
  {
    id: "req-101",
    request_type: "equipment",
    item_name: "ICU Bed & Ventilator",
    generic_name: null,
    quantity: 1,
    urgency: "critical",
    patient_condition: "Severe respiratory distress, SpO2 dropping to 82%",
    requester_name: "Suresh Sharma",
    requester_phone: "9876543210",
    city: "New Delhi",
    state: "Delhi",
    district: "South Delhi",
    pincode: "110029",
    lat: 28.5672,
    lng: 77.2100,
    notes: "Patient waiting outside AIIMS Emergency block. Need ICU bed immediately.",
    status: "open",
    fulfilled_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: "req-102",
    request_type: "medicine",
    item_name: "Remdesivir 100mg Injection",
    generic_name: "Remdesivir",
    quantity: 6,
    urgency: "critical",
    patient_condition: "Viral pneumonia in ICU care",
    requester_name: "Ananya Deshmukh",
    requester_phone: "9812345678",
    city: "Mumbai",
    state: "Maharashtra",
    district: "Mumbai Suburban",
    pincode: "400050",
    lat: 19.0514,
    lng: 72.8286,
    notes: "Lilavati Hospital prescription available. Urgent requirement.",
    status: "open",
    fulfilled_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: "req-103",
    request_type: "equipment",
    item_name: "Oxygen Concentrator (10L)",
    generic_name: null,
    quantity: 2,
    urgency: "urgent",
    patient_condition: "Post-surgery pulmonary recovery at home",
    requester_name: "Karthik Subramanian",
    requester_phone: "9443322110",
    city: "Chennai",
    state: "Tamil Nadu",
    district: "Chennai",
    pincode: "600006",
    lat: 13.0604,
    lng: 80.2496,
    notes: "Home setup near Greams road Chennai.",
    status: "open",
    fulfilled_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: "req-104",
    request_type: "equipment",
    item_name: "ALS Ambulance with Cardiac Monitor",
    generic_name: null,
    quantity: 1,
    urgency: "critical",
    patient_condition: "Acute Myocardial Infarction (Heart Attack)",
    requester_name: "Venkatesh Rao",
    requester_phone: "9988776655",
    city: "Bengaluru",
    state: "Karnataka",
    district: "Bengaluru Urban",
    pincode: "560017",
    lat: 12.9585,
    lng: 77.6484,
    notes: "Inter-hospital transfer from Indiranagar to Manipal HAL road.",
    status: "open",
    fulfilled_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  }
];
