export interface DetailedMedicine {
  id: string;
  name: string;
  genericName: string;
  category: "Antibiotic" | "Analgesic" | "Antiviral" | "Cardiac" | "Diabetic" | "Respiratory" | "Gastro" | "Dermatology" | "Vitamin" | "First-Aid" | "Mental Health" | "Women Health" | "General";
  form: string;
  manufacturer: string;
  prescriptionRequired: boolean;
  description: string;
  uses: string[];
  mechanismOfAction: string;
  standardDosage: string;
  sideEffects: string[];
  precautions: string[];
  storageInfo: string;
  pricePerUnit: number;
  genericAlternative: {
    name: string;
    genericName: string;
    manufacturer: string;
    avgPrice: number;
    savingsPercent: number;
  };
}

export const DETAILED_MEDICINES: DetailedMedicine[] = [
  // --- ORIGINAL 12 MEDICINES ---
  {
    id: "med-dolo-650",
    name: "Dolo 650",
    genericName: "Paracetamol 650mg",
    category: "Analgesic",
    form: "Tablet",
    manufacturer: "Micro Labs Ltd",
    prescriptionRequired: false,
    description: "Widely prescribed antipyretic and analgesic for quick relief from high fever, body ache, and headaches.",
    uses: ["High fever reduction", "Headache & migraine relief", "Body pain & joint stiffness", "Post-vaccination fever"],
    mechanismOfAction: "Selectively inhibits central nervous system prostaglandin synthesis via COX enzyme pathway to lower fever thermostat in hypothalamus.",
    standardDosage: "1 tablet (650mg) every 4–6 hours as needed after meals. Maximum 4 tablets (2600mg) per 24 hours.",
    sideEffects: ["Mild nausea", "Excessive sweating", "Stomach irritation (rare)", "Transient dizziness"],
    precautions: ["Avoid alcohol consumption (risk of liver toxicity)", "Consult physician if liver or renal dysfunction", "Do not combine with other paracetamol products"],
    storageInfo: "Store below 25°C in a cool, dry place away from direct sunlight.",
    pricePerUnit: 12.50,
    genericAlternative: {
      name: "Paracetamol 650 (Jan Aushadhi)",
      genericName: "Paracetamol 650mg",
      manufacturer: "Pradhan Mantri Bhartiya Janaushadhi Pariyanjana (PMBJP)",
      avgPrice: 3.50,
      savingsPercent: 72,
    },
  },
  {
    id: "med-crocin-advance",
    name: "Crocin Advance",
    genericName: "Paracetamol 650mg (Fast Release)",
    category: "Analgesic",
    form: "Tablet",
    manufacturer: "GSK Consumer Healthcare",
    prescriptionRequired: false,
    description: "Fast-acting pain reliever with Optizorb technology that releases medicine 5x faster than standard paracetamol.",
    uses: ["Acute fever", "Severe headache", "Toothache & dental pain", "Musculoskeletal pain"],
    mechanismOfAction: "Optizorb technology disintegrates rapid-release paracetamol in stomach within 5 mins to block pain signaling.",
    standardDosage: "1 tablet every 4–6 hours after food. Maximum 4000mg per 24 hours.",
    sideEffects: ["Mild indigestion", "Skin redness (rare)", "Nausea"],
    precautions: ["Limit treatment duration to 3 consecutive days for fever without medical advice", "Avoid in active liver cirrhosis"],
    storageInfo: "Store in moisture-resistant strip below 30°C.",
    pricePerUnit: 14.00,
    genericAlternative: {
      name: "P-650 Generic",
      genericName: "Paracetamol 650mg",
      manufacturer: "Cipla Generic",
      avgPrice: 4.00,
      savingsPercent: 71,
    },
  },
  {
    id: "med-augmentin-625",
    name: "Augmentin 625 Duo",
    genericName: "Amoxicillin (500mg) + Clavulanic Acid (125mg)",
    category: "Antibiotic",
    form: "Film-coated Tablet",
    manufacturer: "GlaxoSmithKline (GSK)",
    prescriptionRequired: true,
    description: "Broad-spectrum penicillin antibiotic combined with a beta-lactamase inhibitor to overcome bacterial resistance.",
    uses: ["Upper & lower respiratory tract infections", "Sinusitis & tonsillitis", "Urinary tract infections (UTI)", "Skin & soft tissue infections"],
    mechanismOfAction: "Amoxicillin inhibits bacterial cell wall synthesis while Clavulanate inactivates beta-lactamase enzymes produced by resistant bacteria.",
    standardDosage: "1 tablet twice daily (every 12 hours) at the start of a meal for 5 to 7 days.",
    sideEffects: ["Diarrhea & loose stools", "Nausea & vomiting", "Abdominal discomfort", "Skin rash or hives"],
    precautions: ["Complete full course even if symptoms improve", "Contraindicated in Penicillin allergy", "Monitor liver enzymes on prolonged use"],
    storageInfo: "Store in cool dry place below 25°C in original moisture-proof foil.",
    pricePerUnit: 22.50,
    genericAlternative: {
      name: "Amoxy-Clav 625 (Jan Aushadhi)",
      genericName: "Amoxicillin 500mg + Clavulanate 125mg",
      manufacturer: "PMBJP Jan Aushadhi",
      avgPrice: 6.80,
      savingsPercent: 70,
    },
  },
  {
    id: "med-azithral-500",
    name: "Azithral 500",
    genericName: "Azithromycin 500mg",
    category: "Antibiotic",
    form: "Tablet",
    manufacturer: "Alembic Pharmaceuticals",
    prescriptionRequired: true,
    description: "Macrolide antibiotic widely used for short 3-day courses in treating bacterial chest, throat, and skin infections.",
    uses: ["Community-acquired pneumonia", "Strep throat & bronchitis", "Typhoid fever & gastroenteritis", "Chlamydia & pelvic infections"],
    mechanismOfAction: "Binds to 50S ribosomal subunit of susceptible bacteria, inhibiting RNA-dependent protein synthesis.",
    standardDosage: "1 tablet (500mg) once daily 1 hour before or 2 hours after meals for 3 to 5 days.",
    sideEffects: ["Diarrhea", "Abdominal cramps", "Nausea", "Headache", "Reversible hearing change (rare)"],
    precautions: ["Use with caution in QT prolongation or cardiac arrhythmia", "Avoid antacids containing aluminum/magnesium simultaneously"],
    storageInfo: "Store below 30°C protected from light and humidity.",
    pricePerUnit: 24.00,
    genericAlternative: {
      name: "Azithromycin 500 (Jan Aushadhi)",
      genericName: "Azithromycin 500mg",
      manufacturer: "PMBJP",
      avgPrice: 7.20,
      savingsPercent: 70,
    },
  },
  {
    id: "med-glycomet-500",
    name: "Glycomet 500 / Metformin",
    genericName: "Metformin Hydrochloride 500mg",
    category: "Diabetic",
    form: "Sustained Release Tablet",
    manufacturer: "USV Pvt Ltd",
    prescriptionRequired: true,
    description: "First-line oral anti-diabetic agent for managing blood sugar levels in Type 2 Diabetes Mellitus.",
    uses: ["Type 2 Diabetes Mellitus", "Insulin resistance management", "Polycystic Ovary Syndrome (PCOS)", "Prediabetes glycemic control"],
    mechanismOfAction: "Decreases hepatic glucose production, decreases intestinal absorption of glucose, and improves insulin sensitivity.",
    standardDosage: "1 tablet once or twice daily immediately after meals to reduce stomach distress.",
    sideEffects: ["Nausea & bloating", "Metallic taste in mouth", "Diarrhea (initial days)", "Vitamin B12 deficiency on long-term use"],
    precautions: ["Monitor kidney function (eGFR > 30 required)", "Discontinue prior to iodinated radiocontrast imaging", "Avoid heavy alcohol intake"],
    storageInfo: "Store at room temperature 15°C–30°C.",
    pricePerUnit: 5.50,
    genericAlternative: {
      name: "Metformin SR 500 (Jan Aushadhi)",
      genericName: "Metformin 500mg SR",
      manufacturer: "PMBJP",
      avgPrice: 1.60,
      savingsPercent: 71,
    },
  },
  {
    id: "med-pantocid-40",
    name: "Pantocid 40 / Pan 40",
    genericName: "Pantoprazole 40mg",
    category: "Gastro",
    form: "Enteric Coated Tablet",
    manufacturer: "Sun Pharma / Alkem",
    prescriptionRequired: true,
    description: "Proton Pump Inhibitor (PPI) that significantly reduces stomach acid production to heal ulcers and acidity.",
    uses: ["Gastroesophageal Reflux Disease (GERD)", "Peptic & duodenal ulcers", "Acid indigestion & heart burn", "Zollinger-Ellison syndrome"],
    mechanismOfAction: "Irreversibly inhibits the H+/K+ ATPase enzyme (proton pump) in parietal cells of gastric mucosa.",
    standardDosage: "1 tablet (40mg) daily in the morning 30 minutes before breakfast with full glass of water.",
    sideEffects: ["Headache", "Flatulence & gas", "Dry mouth", "Mild diarrhea or constipation"],
    precautions: ["Long term use (>1 year) may decrease magnesium and calcium absorption", "Swallow whole — do not crush or chew tablet"],
    storageInfo: "Store below 25°C in moisture barrier strip.",
    pricePerUnit: 14.50,
    genericAlternative: {
      name: "Pantoprazole 40 (Jan Aushadhi)",
      genericName: "Pantoprazole 40mg EC",
      manufacturer: "PMBJP",
      avgPrice: 3.20,
      savingsPercent: 78,
    },
  },
  {
    id: "med-telma-40",
    name: "Telma 40",
    genericName: "Telmisartan 40mg",
    category: "Cardiac",
    form: "Tablet",
    manufacturer: "Glenmark Pharmaceuticals",
    prescriptionRequired: true,
    description: "Long-acting Angiotensin II Receptor Blocker (ARB) for controlling high blood pressure and protecting kidney function.",
    uses: ["Essential hypertension (High BP)", "Cardiovascular risk reduction", "Diabetic nephropathy protection"],
    mechanismOfAction: "Selectively blocks angiotensin II type-1 (AT1) receptors, causing vascular smooth muscle relaxation and BP reduction.",
    standardDosage: "1 tablet once daily morning or evening, with or without food.",
    sideEffects: ["Dizziness on standing", "Sinus congestion", "Back pain", "Hyperkalemia (high potassium)"],
    precautions: ["Contraindicated during pregnancy (fetal toxicity)", "Regularly monitor serum potassium & renal creatinine levels"],
    storageInfo: "Store below 30°C in blister packaging to protect from atmospheric moisture.",
    pricePerUnit: 18.00,
    genericAlternative: {
      name: "Telmisartan 40 (Jan Aushadhi)",
      genericName: "Telmisartan 40mg",
      manufacturer: "PMBJP",
      avgPrice: 3.50,
      savingsPercent: 80,
    },
  },
  {
    id: "med-atorva-10",
    name: "Atorva 10",
    genericName: "Atorvastatin 10mg",
    category: "Cardiac",
    form: "Film-coated Tablet",
    manufacturer: "Zydus Cadila",
    prescriptionRequired: true,
    description: "HMG-CoA reductase inhibitor (Statin) used to lower LDL bad cholesterol, triglycerides and prevent heart attacks.",
    uses: ["Hypercholesterolemia (High LDL)", "Atherosclerosis prevention", "Heart attack & stroke prophylaxis", "Post-stent cardiac care"],
    mechanismOfAction: "Competitively inhibits HMG-CoA reductase enzyme in liver, upregulating LDL receptors and clearing cholesterol from blood.",
    standardDosage: "1 tablet (10mg) once daily at bedtime (liver cholesterol synthesis peaks at night).",
    sideEffects: ["Muscle aches (myalgia)", "Mild elevation of liver enzymes", "Constipation or diarrhea", "Joint pain"],
    precautions: ["Report unexplained muscle pain or weakness immediately", "Avoid excessive grapefruit juice intake"],
    storageInfo: "Store between 20°C–25°C.",
    pricePerUnit: 15.00,
    genericAlternative: {
      name: "Atorvastatin 10 (Jan Aushadhi)",
      genericName: "Atorvastatin 10mg",
      manufacturer: "PMBJP",
      avgPrice: 2.80,
      savingsPercent: 81,
    },
  },
  {
    id: "med-montair-lc",
    name: "Montair LC",
    genericName: "Montelukast (10mg) + Levocetirizine (5mg)",
    category: "Respiratory",
    form: "Tablet",
    manufacturer: "Cipla Ltd",
    prescriptionRequired: true,
    description: "Dual-action antiallergic & leukotriene receptor antagonist for allergic rhinitis, sneezing, asthma, and dust allergies.",
    uses: ["Allergic rhinitis & seasonal allergies", "Bronchial asthma prevention", "Chronic urticaria & hives", "Nasal congestion & runny nose"],
    mechanismOfAction: "Levocetirizine blocks histamine H1 receptors; Montelukast blocks cysteinyl leukotriene CysLT1 receptors in airways.",
    standardDosage: "1 tablet once daily at night before sleep.",
    sideEffects: ["Drowsiness / sedation", "Dry mouth", "Headache", "Abdominal discomfort"],
    precautions: ["May cause mild drowsiness — caution while driving", "Report unusual mood changes or sleep disturbances"],
    storageInfo: "Store below 25°C away from humidity.",
    pricePerUnit: 20.00,
    genericAlternative: {
      name: "Montelukast 10 + Levocet 5 (Jan Aushadhi)",
      genericName: "Montelukast + Levocetirizine",
      manufacturer: "PMBJP",
      avgPrice: 5.00,
      savingsPercent: 75,
    },
  },
  {
    id: "med-asthalin-inhaler",
    name: "Asthalin Inhaler",
    genericName: "Salbutamol / Albuterol 100mcg per puff",
    category: "Respiratory",
    form: "Metered Dose Inhaler (MDI)",
    manufacturer: "Cipla Ltd",
    prescriptionRequired: true,
    description: "Short-acting beta-2 agonist (SABA) rescue bronchodilator for fast relief from acute asthma attacks and breathlessness.",
    uses: ["Acute asthma attack relief", "Bronchospasm & wheezing", "COPD breathlessness", "Exercise-induced asthma"],
    mechanismOfAction: "Stimulates beta-2 adrenergic receptors in bronchial smooth muscle, causing rapid bronchodilation within 5 minutes.",
    standardDosage: "1 to 2 puffs inhaled when breathlessness occurs. Maximum 8 puffs in 24 hours.",
    sideEffects: ["Fine hand tremors", "Increased heart rate (palpitations)", "Transient headache", "Throat irritation"],
    precautions: ["Rinse mouth with water after inhalation", "If rescue inhaler needed >3 times a week, consult doctor to adjust controller therapy"],
    storageInfo: "Store below 30°C. Do not puncture canister or expose to extreme heat.",
    pricePerUnit: 165.00,
    genericAlternative: {
      name: "Salbutamol Inhaler 100mcg",
      genericName: "Salbutamol Inhaler",
      manufacturer: "PMBJP",
      avgPrice: 65.00,
      savingsPercent: 60,
    },
  },
  {
    id: "med-combiflam",
    name: "Combiflam",
    genericName: "Ibuprofen (400mg) + Paracetamol (325mg)",
    category: "Analgesic",
    form: "Tablet",
    manufacturer: "Sanofi India",
    prescriptionRequired: false,
    description: "Combination NSAID & analgesic providing potent dual-action relief for inflammatory pain, dental pain, and high fever.",
    uses: ["Rheumatoid & osteoarthritis pain", "Dental pain & tooth extraction", "Post-operative swelling & pain", "Sprains & muscle trauma"],
    mechanismOfAction: "Ibuprofen inhibits peripheral COX-1 & COX-2 enzymes reducing inflammation, while Paracetamol acts centrally on pain pathways.",
    standardDosage: "1 tablet 2 to 3 times daily strictly after meals.",
    sideEffects: ["Gastric acidity & heartburn", "Nausea", "Dizziness", "Abdominal discomfort"],
    precautions: ["Always take with food or milk to prevent gastric ulceration", "Avoid in active peptic ulcer disease or severe kidney failure"],
    storageInfo: "Store below 25°C in dry place.",
    pricePerUnit: 5.50,
    genericAlternative: {
      name: "Ibuprofen + Paracetamol (Jan Aushadhi)",
      genericName: "Ibuprofen 400 + Paracetamol 325",
      manufacturer: "PMBJP",
      avgPrice: 1.50,
      savingsPercent: 73,
    },
  },
  {
    id: "med-insulin-lantus",
    name: "Lantus / Insulin Glargine",
    genericName: "Insulin Glargine 100 IU/ml",
    category: "Diabetic",
    form: "Injection / Cartridge / Pen",
    manufacturer: "Sanofi India",
    prescriptionRequired: true,
    description: "Long-acting basal human insulin analogue providing flat, 24-hour continuous glycemic control without sharp peaks.",
    uses: ["Type 1 Diabetes Mellitus", "Type 2 Diabetes uncontrolled by oral meds"],
    mechanismOfAction: "Formulates micro-precipitates in subcutaneous tissue releasing insulin slowly over 24 hours to promote cellular glucose uptake.",
    standardDosage: "Injected subcutaneously once daily at the same time every day (bedtime or morning). Dosage as individualized by endocrinologist.",
    sideEffects: ["Hypoglycemia (low blood sugar)", "Injection site redness/lipodystrophy", "Weight gain", "Mild peripheral edema"],
    precautions: ["Never inject into vein or muscle", "Keep quick glucose source (candy/juice) accessible at all times for hypoglycemia emergencies"],
    storageInfo: "Store unopened pens in refrigerator (2°C–8°C). In-use pen can remain at room temperature (<30°C) up to 28 days.",
    pricePerUnit: 850.00,
    genericAlternative: {
      name: "Insulin Glargine Jan Aushadhi",
      genericName: "Insulin Glargine 100IU",
      manufacturer: "PMBJP / Biocon",
      avgPrice: 420.00,
      savingsPercent: 50,
    },
  },

  // --- NEW ADDITIONS (13 to 50) ---
  {
    id: "med-cifran-500",
    name: "Cifran 500",
    genericName: "Ciprofloxacin 500mg",
    category: "Antibiotic",
    form: "Tablet",
    manufacturer: "Sun Pharmaceutical Industries",
    prescriptionRequired: true,
    description: "Fluoroquinolone antibiotic used to treat bacterial infections of the urinary tract, joints, bones, and gastrointestinal system.",
    uses: ["Urinary tract infections (UTI)", "Typhoid fever & infectious diarrhea", "Prostatitis", "Bone and joint infections"],
    mechanismOfAction: "Inhibits bacterial DNA gyrase and topoisomerase IV enzymes required for bacterial DNA replication and repair.",
    standardDosage: "1 tablet (500mg) every 12 hours for 5 to 14 days based on infection severity.",
    sideEffects: ["Nausea & diarrhea", "Tendinitis / tendon rupture (rare)", "Dizziness", "Photosensitivity"],
    precautions: ["Avoid co-administration with dairy or calcium-fortified products", "Discontinue if tendon pain or swelling occurs"],
    storageInfo: "Store below 30°C protected from light.",
    pricePerUnit: 9.50,
    genericAlternative: {
      name: "Ciprofloxacin 500 (Jan Aushadhi)",
      genericName: "Ciprofloxacin 500mg",
      manufacturer: "PMBJP",
      avgPrice: 2.20,
      savingsPercent: 77,
    },
  },
  {
    id: "med-taxim-o-200",
    name: "Taxim-O 200",
    genericName: "Cefixime 200mg",
    category: "Antibiotic",
    form: "Tablet",
    manufacturer: "Alkem Laboratories",
    prescriptionRequired: true,
    description: "Oral third-generation cephalosporin antibiotic effective against a wide array of Gram-negative and Gram-positive bacteria.",
    uses: ["Typhoid fever", "Otitis media (middle ear infection)", "Tonsillitis & pharyngitis", "Uncomplicated UTI"],
    mechanismOfAction: "Inhibits bacterial cell wall synthesis by binding to penicillin-binding proteins (PBPs).",
    standardDosage: "1 tablet (200mg) twice daily for 5 to 10 days.",
    sideEffects: ["Loose stools / diarrhea", "Abdominal pain", "Dyspepsia", "Skin rash"],
    precautions: ["Use with caution in patients with cephalosporin or penicillin hypersensitivity", "Reduce dosage in renal impairment"],
    storageInfo: "Store below 25°C in a cool, dry place.",
    pricePerUnit: 16.50,
    genericAlternative: {
      name: "Cefixime 200 (Jan Aushadhi)",
      genericName: "Cefixime 200mg",
      manufacturer: "PMBJP",
      avgPrice: 4.80,
      savingsPercent: 71,
    },
  },
  {
    id: "med-flagyl-400",
    name: "Flagyl 400",
    genericName: "Metronidazole 400mg",
    category: "Antibiotic",
    form: "Tablet",
    manufacturer: "Abbott Healthcare",
    prescriptionRequired: true,
    description: "Antimicrobial & antiprotozoal medication effective against anaerobic bacteria and intestinal protozoal parasites.",
    uses: ["Amebiasis & giardiasis", "Anaerobic bacterial infections", "Dental abscesses", "Trichomoniasis"],
    mechanismOfAction: "Forms reactive cytotoxic intermediates inside anaerobic microorganisms that damage bacterial DNA and inhibit nucleic acid synthesis.",
    standardDosage: "1 tablet (400mg) 3 times daily after meals for 5 to 7 days.",
    sideEffects: ["Metallic taste in mouth", "Nausea & dark urine", "Loss of appetite", "Headache"],
    precautions: ["STRICTLY avoid alcohol during treatment and 48 hours post-treatment (causes disulfiram-like severe reaction)", "Caution in CNS disorders"],
    storageInfo: "Store below 30°C away from direct sunlight.",
    pricePerUnit: 2.20,
    genericAlternative: {
      name: "Metronidazole 400 (Jan Aushadhi)",
      genericName: "Metronidazole 400mg",
      manufacturer: "PMBJP",
      avgPrice: 0.70,
      savingsPercent: 68,
    },
  },
  {
    id: "med-zocon-150",
    name: "Zocon 150",
    genericName: "Fluconazole 150mg",
    category: "Antibiotic",
    form: "Tablet",
    manufacturer: "FDC Ltd",
    prescriptionRequired: false,
    description: "Potent triazole antifungal medication single-dose therapy for yeast infections and fungal cutaneous conditions.",
    uses: ["Vaginal candidiasis (yeast infection)", "Oral thrush", "Tinea corporis & cruris (ringworm/jock itch)", "Fungal nail infections"],
    mechanismOfAction: "Selectively inhibits fungal cytochrome P450-dependent enzyme lanosterol 14-alpha-demethylase, disrupting fungal cell membrane.",
    standardDosage: "Single dose of 150mg tablet, or as directed weekly by dermatologist.",
    sideEffects: ["Mild headache", "Nausea", "Abdominal pain", "Diarrhea"],
    precautions: ["Caution in renal or hepatic dysfunction", "Avoid in pregnancy unless deemed essential by OB/GYN"],
    storageInfo: "Store below 25°C in dry conditions.",
    pricePerUnit: 14.00,
    genericAlternative: {
      name: "Fluconazole 150 (Jan Aushadhi)",
      genericName: "Fluconazole 150mg",
      manufacturer: "PMBJP",
      avgPrice: 3.00,
      savingsPercent: 78,
    },
  },
  {
    id: "med-meftal-spas",
    name: "Meftal-Spas",
    genericName: "Mefenamic Acid (250mg) + Dicyclomine HCl (10mg)",
    category: "Analgesic",
    form: "Tablet",
    manufacturer: "Blue Cross Laboratories",
    prescriptionRequired: true,
    description: "Antispasmodic and analgesic combination designed to soothe smooth muscle spasms and visceral abdominal pain.",
    uses: ["Menstrual cramps (dysmenorrhea)", "Intestinal colic", "Biliary & renal colic pain", "Spasmodic abdominal pain"],
    mechanismOfAction: "Dicyclomine relaxes smooth muscles of gut/uterus via anticholinergic action; Mefenamic Acid blocks pain-causing prostaglandins.",
    standardDosage: "1 tablet 2 to 3 times daily after food during painful spasm episodes.",
    sideEffects: ["Dry mouth", "Blurred vision", "Drowsiness", "Dizziness"],
    precautions: ["Caution in glaucoma and urinary retention", "Avoid driving due to potential drowsiness"],
    storageInfo: "Store below 30°C in original strip.",
    pricePerUnit: 5.80,
    genericAlternative: {
      name: "Mefenamic + Dicyclomine (Jan Aushadhi)",
      genericName: "Mefenamic Acid 250mg + Dicyclomine 10mg",
      manufacturer: "PMBJP",
      avgPrice: 1.80,
      savingsPercent: 69,
    },
  },
  {
    id: "med-zerodol-p",
    name: "Zerodol-P",
    genericName: "Aceclofenac (100mg) + Paracetamol (325mg)",
    category: "Analgesic",
    form: "Tablet",
    manufacturer: "Ipca Laboratories",
    prescriptionRequired: true,
    description: "Popular NSAID combination offering rapid anti-inflammatory and analgesic action for joint and post-trauma pain.",
    uses: ["Osteoarthritis & Rheumatoid Arthritis", "Ankylosing spondylitis", "Post-surgical pain", "Dental & joint inflammation"],
    mechanismOfAction: "Aceclofenac inhibits COX enzyme synthesis to suppress prostaglandin production at inflammatory sites.",
    standardDosage: "1 tablet twice daily after meals (morning and evening).",
    sideEffects: ["Epigastric pain", "Nausea", "Heartburn", "Dizziness"],
    precautions: ["Contraindicated in severe heart failure or active GI bleeding", "Always consume with adequate food"],
    storageInfo: "Store below 25°C away from moisture.",
    pricePerUnit: 6.50,
    genericAlternative: {
      name: "Aceclofenac + Paracetamol (Jan Aushadhi)",
      genericName: "Aceclofenac 100mg + Paracetamol 325mg",
      manufacturer: "PMBJP",
      avgPrice: 1.90,
      savingsPercent: 70,
    },
  },
  {
    id: "med-ultracet",
    name: "Ultracet",
    genericName: "Tramadol HCl (37.5mg) + Paracetamol (325mg)",
    category: "Analgesic",
    form: "Film-coated Tablet",
    manufacturer: "Janssen Pharmaceuticals / Johnson & Johnson",
    prescriptionRequired: true,
    description: "Centrally acting prescription analgesic for moderate to severe pain relief combining opioid receptor binding with antipyretic action.",
    uses: ["Post-operative surgical pain", "Severe acute musculoskeletal pain", "Neuropathic pain flare-ups", "Fracture trauma pain"],
    mechanismOfAction: "Tramadol binds mu-opioid receptors and inhibits reuptake of norepinephrine/serotonin; Paracetamol raises pain threshold.",
    standardDosage: "1 to 2 tablets every 4 to 6 hours as needed. Maximum 8 tablets per day.",
    sideEffects: ["Drowsiness & dizziness", "Constipation", "Nausea", "Dry mouth"],
    precautions: ["High risk of habituation/dependence with prolonged unmonitored use", "Do not combine with SSRIs/SNRIs without psychiatric guidance"],
    storageInfo: "Store below 30°C under lock or restricted access.",
    pricePerUnit: 22.00,
    genericAlternative: {
      name: "Tramadol + Paracetamol (Jan Aushadhi)",
      genericName: "Tramadol 37.5mg + Paracetamol 325mg",
      manufacturer: "PMBJP",
      avgPrice: 5.50,
      savingsPercent: 75,
    },
  },
  {
    id: "med-covifor-remdesivir",
    name: "Covifor / Remdesivir",
    genericName: "Remdesivir 100mg",
    category: "Antiviral",
    form: "Intravenous Injection",
    manufacturer: "Hetero Drugs / Gilead Sciences",
    prescriptionRequired: true,
    description: "Nucleoside RNA polymerase inhibitor designed for intravenous hospital administration in severe viral respiratory infections.",
    uses: ["Hospitalized COVID-19 management", "Severe acute respiratory coronavirus infections"],
    mechanismOfAction: "Acts as an adenosine analogue that incorporates into viral RNA chains, causing premature termination of RNA synthesis.",
    standardDosage: "200mg IV loading dose on Day 1, followed by 100mg IV once daily for 5 days under strict hospital supervision.",
    sideEffects: ["Elevated liver transaminases", "Infusion-related reactions", "Nausea", "Bradycardia"],
    precautions: ["Monitor hepatic transaminases and eGFR before and during treatment", "Administer exclusively in clinical healthcare setups"],
    storageInfo: "Store vial below 30°C or refrigerated as per manufacturer guidelines.",
    pricePerUnit: 2800.00,
    genericAlternative: {
      name: "Remdesivir Generic IV",
      genericName: "Remdesivir 100mg",
      manufacturer: "Zydus / Cipla",
      avgPrice: 1200.00,
      savingsPercent: 57,
    },
  },
  {
    id: "med-valcivir-1000",
    name: "Valcivir 1000",
    genericName: "Valacyclovir 1000mg",
    category: "Antiviral",
    form: "Tablet",
    manufacturer: "Cipla Ltd",
    prescriptionRequired: true,
    description: "Prodrug of acyclovir with enhanced oral bioavailability used for the treatment and suppression of herpes viral infections.",
    uses: ["Herpes Zoster (Shingles)", "Genital Herpes lesions", "Herpes Labialis (Cold sores)", "Cytomegalovirus prophylaxis"],
    mechanismOfAction: "Rapidly converted to acyclovir, which selectively inhibits herpes viral DNA polymerase, halting viral replication.",
    standardDosage: "1 tablet (1000mg) 3 times daily for 7 days for Shingles.",
    sideEffects: ["Headache", "Nausea", "Abdominal pain", "Dizziness"],
    precautions: ["Maintain high fluid intake to prevent renal crystalluria", "Adjust dose in elderly patients or kidney impairment"],
    storageInfo: "Store below 25°C away from light.",
    pricePerUnit: 85.00,
    genericAlternative: {
      name: "Valacyclovir 1000 (Jan Aushadhi)",
      genericName: "Valacyclovir 1000mg",
      manufacturer: "PMBJP",
      avgPrice: 28.00,
      savingsPercent: 67,
    },
  },
  {
    id: "med-amlong-5",
    name: "Amlong 5",
    genericName: "Amlodipine Besylate 5mg",
    category: "Cardiac",
    form: "Tablet",
    manufacturer: "Micro Labs Ltd",
    prescriptionRequired: true,
    description: "Dihydropyridine Calcium Channel Blocker (CCB) widely prescribed for long-term control of high blood pressure and angina.",
    uses: ["Essential hypertension", "Chronic stable angina", "Vasospastic (Prinzmetal's) angina"],
    mechanismOfAction: "Inhibits calcium ion influx into vascular smooth muscle cells and cardiac muscle, producing peripheral arterial vasodilation.",
    standardDosage: "1 tablet (5mg) once daily, increased to maximum 10mg once daily if needed.",
    sideEffects: ["Ankle edema (swelling)", "Flushing", "Palpitations", "Fatigue"],
    precautions: ["Caution in severe aortic stenosis or hepatic impairment", "Do not stop abruptly without medical advice"],
    storageInfo: "Store below 30°C protected from moisture.",
    pricePerUnit: 3.20,
    genericAlternative: {
      name: "Amlodipine 5 (Jan Aushadhi)",
      genericName: "Amlodipine 5mg",
      manufacturer: "PMBJP",
      avgPrice: 0.60,
      savingsPercent: 81,
    },
  },
  {
    id: "med-concor-5",
    name: "Concor 5",
    genericName: "Bisoprolol Fumarate 5mg",
    category: "Cardiac",
    form: "Tablet",
    manufacturer: "Merck Ltd",
    prescriptionRequired: true,
    description: "Cardioselective beta-1 adrenergic receptor blocker used to reduce heart rate, myocardial oxygen demand, and blood pressure.",
    uses: ["Hypertension", "Angina pectoris", "Stable chronic heart failure with reduced ejection fraction"],
    mechanismOfAction: "Selectively blocks beta-1 receptors in heart tissue, decreasing heart rate, cardiac output, and renin release from kidneys.",
    standardDosage: "1 tablet (5mg) once daily in the morning.",
    sideEffects: ["Slow heart rate (bradycardia)", "Cold extremities", "Fatigue", "Sleep disturbances"],
    precautions: ["Never stop abruptly (risk of rebound tachycardia or cardiac events)", "Use with extreme care in asthma or COPD"],
    storageInfo: "Store below 25°C.",
    pricePerUnit: 11.50,
    genericAlternative: {
      name: "Bisoprolol 5 (Jan Aushadhi)",
      genericName: "Bisoprolol 5mg",
      manufacturer: "PMBJP",
      avgPrice: 2.50,
      savingsPercent: 78,
    },
  },
  {
    id: "med-ecospirin-75",
    name: "Ecospirin 75",
    genericName: "Aspirin / Acetylsalicylic Acid 75mg",
    category: "Cardiac",
    form: "Enteric Coated Tablet",
    manufacturer: "USV Pvt Ltd",
    prescriptionRequired: true,
    description: "Low-dose antiplatelet agent essential for preventing blood clot formation in cardiovascular and cerebrovascular conditions.",
    uses: ["Myocardial infarction (Heart attack) prevention", "Ischemic stroke prevention", "Post-angioplasty stent maintenance", "Angina pectoris"],
    mechanismOfAction: "Irreversibly acetylates COX-1 enzyme in platelets, preventing thromboxane A2 synthesis and platelet aggregation for platelet lifespan.",
    standardDosage: "1 tablet (75mg) once daily after principal meal.",
    sideEffects: ["Gastric acidity & irritation", "Increased bleeding tendency / easy bruising", "Dyspepsia"],
    precautions: ["Take with food to minimize gastric mucosal injury", "Inform dentist/surgeon before elective surgical procedures"],
    storageInfo: "Store in cool dry place away from heat.",
    pricePerUnit: 1.20,
    genericAlternative: {
      name: "Aspirin 75 EC (Jan Aushadhi)",
      genericName: "Aspirin 75mg EC",
      manufacturer: "PMBJP",
      avgPrice: 0.35,
      savingsPercent: 71,
    },
  },
  {
    id: "med-sorbitrate-5",
    name: "Sorbitrate 5",
    genericName: "Isosorbide Dinitrate 5mg",
    category: "Cardiac",
    form: "Sublingual Tablet",
    manufacturer: "Abbott Healthcare",
    prescriptionRequired: true,
    description: "Fast-acting vasodilator placed under the tongue for rapid termination or prevention of acute angina pectoris episodes.",
    uses: ["Acute angina attack emergency relief", "Angina prophylaxis prior to physical exertion", "Adjunct in acute heart failure"],
    mechanismOfAction: "Releases nitric oxide (NO) which relaxes vascular smooth muscle, predominantly dilating veins and reducing cardiac preload.",
    standardDosage: "Dissolve 1 tablet under tongue at onset of chest pain. May repeat after 5 mins; maximum 3 tablets in 15 mins.",
    sideEffects: ["Severe throbbing headache", "Reflex tachycardia", "Dizziness & orthostatic hypotension"],
    precautions: ["STRICTLY contraindicated with sildenafil/tadalafil (causes catastrophic BP collapse)", "Sit or lie down when taking sublingually"],
    storageInfo: "Keep tightly closed in original glass vial below 25°C.",
    pricePerUnit: 1.80,
    genericAlternative: {
      name: "Isosorbide Dinitrate 5 (Jan Aushadhi)",
      genericName: "Isosorbide Dinitrate 5mg",
      manufacturer: "PMBJP",
      avgPrice: 0.50,
      savingsPercent: 72,
    },
  },
  {
    id: "med-januvia-100",
    name: "Januvia 100",
    genericName: "Sitagliptin 100mg",
    category: "Diabetic",
    form: "Film-coated Tablet",
    manufacturer: "MSD Pharmaceuticals",
    prescriptionRequired: true,
    description: "Dipeptidyl peptidase-4 (DPP-4) inhibitor that boosts body's natural incretin hormone levels to regulate blood sugar without weight gain.",
    uses: ["Type 2 Diabetes Mellitus glycemic control", "Combination therapy with Metformin/Sulfonylureas"],
    mechanismOfAction: "Inhibits DPP-4 enzyme, slowing inactivation of incretin hormones (GLP-1), enhancing glucose-dependent insulin secretion.",
    standardDosage: "1 tablet (100mg) once daily with or without food.",
    sideEffects: ["Upper respiratory infection", "Headache", "Hypoglycemia (when combined with sulfonylureas)", "Pancreatitis (rare)"],
    precautions: ["Adjust dosage in moderate-to-severe renal impairment", "Discontinue immediately if severe persistent abdominal pain occurs"],
    storageInfo: "Store below 30°C.",
    pricePerUnit: 42.00,
    genericAlternative: {
      name: "Sitagliptin 100 (Jan Aushadhi)",
      genericName: "Sitagliptin 100mg",
      manufacturer: "PMBJP",
      avgPrice: 12.00,
      savingsPercent: 71,
    },
  },
  {
    id: "med-jardiance-10",
    name: "Jardiance 10",
    genericName: "Empagliflozin 10mg",
    category: "Diabetic",
    form: "Tablet",
    manufacturer: "Boehringer Ingelheim",
    prescriptionRequired: true,
    description: "SGLT2 inhibitor that reduces blood glucose by causing kidneys to excrete excess sugar through urine, offering heart and kidney protection.",
    uses: ["Type 2 Diabetes Mellitus", "Heart failure hospitalization risk reduction", "Chronic kidney disease progression delay"],
    mechanismOfAction: "Inhibits sodium-glucose co-transporter 2 (SGLT2) in proximal renal tubules, lowering renal threshold for glucose.",
    standardDosage: "1 tablet (10mg) once daily in the morning with or without food.",
    sideEffects: ["Urinary tract infections", "Genital mycotic infections (yeast)", "Increased urination", "Mild dehydration"],
    precautions: ["Ensure adequate hydration to avoid hypotension", "Monitor for symptoms of euglycemic diabetic ketoacidosis (DKA)"],
    storageInfo: "Store below 30°C.",
    pricePerUnit: 58.00,
    genericAlternative: {
      name: "Empagliflozin 10 (Jan Aushadhi)",
      genericName: "Empagliflozin 10mg",
      manufacturer: "PMBJP / Micro Labs",
      avgPrice: 16.00,
      savingsPercent: 72,
    },
  },
  {
    id: "med-amaryll-2",
    name: "Amaryl 2",
    genericName: "Glimepiride 2mg",
    category: "Diabetic",
    form: "Tablet",
    manufacturer: "Sanofi India",
    prescriptionRequired: true,
    description: "Second-generation sulfonylurea oral hypoglycemic agent that stimulates pancreas beta cells to produce more insulin.",
    uses: ["Type 2 Diabetes Mellitus management", "Combination therapy with Metformin"],
    mechanismOfAction: "Binds to ATP-sensitive potassium channels on pancreatic beta-cell membranes, causing membrane depolarization and insulin release.",
    standardDosage: "1 tablet (2mg) once daily taken immediately before or with breakfast.",
    sideEffects: ["Hypoglycemia (low blood sugar)", "Weight gain", "Mild nausea", "Dizziness"],
    precautions: ["Never skip meals after taking tablet", "Educate patient on managing hypoglycemic symptoms (sweating, tremors)"],
    storageInfo: "Store below 25°C protected from light.",
    pricePerUnit: 9.80,
    genericAlternative: {
      name: "Glimepiride 2 (Jan Aushadhi)",
      genericName: "Glimepiride 2mg",
      manufacturer: "PMBJP",
      avgPrice: 2.10,
      savingsPercent: 78,
    },
  },
  {
    id: "med-gelusil-mps",
    name: "Gelusil MPS Liquid",
    genericName: "Aluminum Hydroxide + Magnesium Hydroxide + Dimethicone",
    category: "Gastro",
    form: "Antacid Syrup",
    manufacturer: "Pfizer Ltd",
    prescriptionRequired: false,
    description: "Antacid and antiflatulent combination providing fast cooling relief from heartburn, hyperacidity, and trapped intestinal gas.",
    uses: ["Acid reflux & GERD symptoms", "Heartburn", "Stomach bloating & gas distension", "Gastric discomfort after spicy food"],
    mechanismOfAction: "Aluminum and Magnesium hydroxides neutralize existing stomach acid; Dimethicone lowers surface tension of gas bubbles to merge them.",
    standardDosage: "2 to 4 teaspoonfuls (10–20ml) 30 to 60 minutes after meals and at bedtime.",
    sideEffects: ["Constipation (from Aluminum)", "Mild diarrhea (from Magnesium)", "Chalky taste"],
    precautions: ["Separate intake by 2 hours from antibiotics like Ciprofloxacin or Tetracycline", "Avoid chronic use in severe kidney disease"],
    storageInfo: "Store below 30°C. Shake bottle well before use.",
    pricePerUnit: 120.00,
    genericAlternative: {
      name: "Antacid + Antiflatulent Syrup (Jan Aushadhi)",
      genericName: "Aluminium Hydroxide + Magnesium + Dimethicone",
      manufacturer: "PMBJP",
      avgPrice: 45.00,
      savingsPercent: 62,
    },
  },
  {
    id: "med-duphalac-syrup",
    name: "Duphalac Syrup",
    genericName: "Lactulose 10g / 15ml",
    category: "Gastro",
    form: "Oral Solution",
    manufacturer: "Abbott India",
    prescriptionRequired: false,
    description: "Non-absorbable synthetic sugar osmotic laxative used for gentle constipation relief and hepatic encephalopathy management.",
    uses: ["Chronic constipation", "Softening stool for hemorrhoids/fissures", "Hepatic encephalopathy prophylaxis"],
    mechanismOfAction: "Broken down by colonic bacteria into organic acids, drawing water into the colon via osmosis to soften stool and promote peristalsis.",
    standardDosage: "15ml to 30ml once daily in the morning with breakfast or diluted in water/juice.",
    sideEffects: ["Flatulence & abdominal cramps", "Nausea", "Diarrhea (if over-dosed)"],
    precautions: ["May take 24–48 hours to produce results", "Use with caution in patients with galactosemia or lactose intolerance"],
    storageInfo: "Store between 15°C–30°C. Do not freeze.",
    pricePerUnit: 210.00,
    genericAlternative: {
      name: "Lactulose Solution (Jan Aushadhi)",
      genericName: "Lactulose 10g/15ml",
      manufacturer: "PMBJP",
      avgPrice: 85.00,
      savingsPercent: 59,
    },
  },
  {
    id: "med-ondem-4",
    name: "Ondem 4",
    genericName: "Ondansetron 4mg",
    category: "Gastro",
    form: "Tablet / ODT",
    manufacturer: "Alkem Laboratories",
    prescriptionRequired: true,
    description: "Selective serotonin 5-HT3 receptor antagonist used to prevent and suppress severe nausea and vomiting.",
    uses: ["Chemotherapy/radiation induced nausea", "Post-operative nausea & vomiting", "Gastroenteritis acute vomiting"],
    mechanismOfAction: "Blocks 5-HT3 serotonin receptors peripherally on vagus nerve terminals and centrally in the chemoreceptor trigger zone (CTZ).",
    standardDosage: "1 tablet (4mg) 30 minutes before meal or chemotherapy; repeat every 8 hours as needed.",
    sideEffects: ["Headache", "Constipation", "Feeling of warmth/flushing", "Transient elevation of liver enzymes"],
    precautions: ["Caution in patients with underlying cardiac conduction abnormalities (QT prolongation)"],
    storageInfo: "Store below 30°C protected from light.",
    pricePerUnit: 5.20,
    genericAlternative: {
      name: "Ondansetron 4 (Jan Aushadhi)",
      genericName: "Ondansetron 4mg",
      manufacturer: "PMBJP",
      avgPrice: 1.20,
      savingsPercent: 76,
    },
  },
  {
    id: "med-allegra-120",
    name: "Allegra 120",
    genericName: "Fexofenadine HCl 120mg",
    category: "Respiratory",
    form: "Tablet",
    manufacturer: "Sanofi India",
    prescriptionRequired: false,
    description: "Non-drowsy second-generation antihistamine offering effective 24-hour relief from allergy symptoms without sedation.",
    uses: ["Seasonal allergic rhinitis", "Sneezing & watery eyes", "Hives & skin allergy (Urticaria)", "Dust & pollen allergy"],
    mechanismOfAction: "Selectively blocks peripheral H1 histamine receptors, preventing histamine-mediated allergic inflammatory cascades.",
    standardDosage: "1 tablet (120mg) once daily with water before meals.",
    sideEffects: ["Headache", "Drowsiness (rare compared to older antihistamines)", "Nausea", "Dry mouth"],
    precautions: ["Do not take with fruit juices (apple, orange, grapefruit) as they reduce drug absorption", "Separate from aluminum/magnesium antacids"],
    storageInfo: "Store below 25°C in dry place.",
    pricePerUnit: 18.00,
    genericAlternative: {
      name: "Fexofenadine 120 (Jan Aushadhi)",
      genericName: "Fexofenadine 120mg",
      manufacturer: "PMBJP",
      avgPrice: 4.50,
      savingsPercent: 75,
    },
  },
  {
    id: "med-budecort-200",
    name: "Budecort 200 Inhaler",
    genericName: "Budesonide 200mcg per puff",
    category: "Respiratory",
    form: "Metered Dose Inhaler",
    manufacturer: "Cipla Ltd",
    prescriptionRequired: true,
    description: "Inhaled corticosteroid (ICS) preventative controller treatment that reduces inflammation and swelling in the bronchial airways.",
    uses: ["Maintenance treatment of Asthma", "COPD symptom management", "Airway hyperresponsiveness reduction"],
    mechanismOfAction: "Potent anti-inflammatory glucocorticoid that suppresses multiple inflammatory cells and cytokine mediator production in lungs.",
    standardDosage: "1 to 2 puffs inhaled twice daily (morning and evening) continuously, regardless of symptom presence.",
    sideEffects: ["Oral candidiasis (thrush)", "Hoarseness of voice (dysphonia)", "Throat irritation", "Cough"],
    precautions: ["ALWAYS rinse mouth thoroughly with water and spit out after inhalation to prevent oral fungal infection", "Not a fast-acting rescue inhaler"],
    storageInfo: "Store below 30°C away from frost and direct heat.",
    pricePerUnit: 310.00,
    genericAlternative: {
      name: "Budesonide Inhaler 200mcg",
      genericName: "Budesonide 200mcg",
      manufacturer: "PMBJP",
      avgPrice: 140.00,
      savingsPercent: 55,
    },
  },
  {
    id: "med-ascoril-ls",
    name: "Ascoril LS Syrup",
    genericName: "Levosalbutamol (1mg) + Ambroxol (30mg) + Guaiphenesin (50mg)",
    category: "Respiratory",
    form: "Expectorant Cough Syrup",
    manufacturer: "Glenmark Pharmaceuticals",
    prescriptionRequired: true,
    description: "Triple-action mucolytic expectorant that thins thick mucus, opens airways, and helps clear chesty productive coughs.",
    uses: ["Productive cough with mucus", "Bronchial asthma with congestion", "Bronchitis & chest congestion", "COPD exacerbation"],
    mechanismOfAction: "Ambroxol thins sputum; Guaiphenesin increases airway fluid release; Levosalbutamol relaxes airway muscles.",
    standardDosage: "10ml (2 teaspoonfuls) 3 times daily after food.",
    sideEffects: ["Tremors", "Palpitations / fast heart rate", "Nausea", "Headache"],
    precautions: ["Caution in hyperthyroidism and cardiac disease", "Drink plenty of warm water to assist mucus thinning"],
    storageInfo: "Store below 30°C in well-closed bottle.",
    pricePerUnit: 135.00,
    genericAlternative: {
      name: "Levosalbutamol + Ambroxol Syrup (Jan Aushadhi)",
      genericName: "Levosalbutamol + Ambroxol + Guaiphenesin",
      manufacturer: "PMBJP",
      avgPrice: 45.00,
      savingsPercent: 67,
    },
  },
  {
    id: "med-nexito-10",
    name: "Nexito 10",
    genericName: "Escitalopram Oxalate 10mg",
    category: "Mental Health",
    form: "Film-coated Tablet",
    manufacturer: "Sun Pharmaceutical Industries",
    prescriptionRequired: true,
    description: "Selective Serotonin Reuptake Inhibitor (SSRI) first-line antidepressant and anti-anxiety prescription medication.",
    uses: ["Major Depressive Disorder (MDD)", "Generalized Anxiety Disorder (GAD)", "Panic Disorder", "Obsessive-Compulsive Disorder (OCD)"],
    mechanismOfAction: "Selectively inhibits presynaptic serotonin reuptake in CNS neurons, increasing serotonergic activity in synaptic cleft.",
    standardDosage: "1 tablet (10mg) once daily in morning or evening. Therapeutic effects take 2 to 4 weeks.",
    sideEffects: ["Nausea & initial agitation", "Sexual dysfunction", "Insomnia or somnolence", "Dry mouth"],
    precautions: ["Do not discontinue abruptly (risk of withdrawal discontinuation syndrome)", "Black box warning: monitor for suicidal ideation in youth"],
    storageInfo: "Store below 25°C.",
    pricePerUnit: 11.00,
    genericAlternative: {
      name: "Escitalopram 10 (Jan Aushadhi)",
      genericName: "Escitalopram 10mg",
      manufacturer: "PMBJP",
      avgPrice: 2.80,
      savingsPercent: 75,
    },
  },
  {
    id: "med-alprax-05",
    name: "Alprax 0.5",
    genericName: "Alprazolam 0.5mg",
    category: "Mental Health",
    form: "Tablet",
    manufacturer: "Torrent Pharmaceuticals",
    prescriptionRequired: true,
    description: "Short-acting benzodiazepine intended for short-term emergency alleviation of severe acute anxiety and panic attacks.",
    uses: ["Acute panic attacks", "Severe short-term anxiety state", "Agitation relief"],
    mechanismOfAction: "Binds to GABA-A benzodiazepine receptor site, enhancing inhibitory neurotransmitter GABA activity in brain.",
    standardDosage: "0.25mg to 0.5mg 2 to 3 times daily strictly under psychiatric monitoring. Use shortest duration possible.",
    sideEffects: ["Sedation & drowsiness", "Memory impairment", "Impaired motor coordination", "Dependence / tolerance"],
    precautions: ["High potential for physical and psychological dependence", "Strictly avoid alcohol (causes severe respiratory depression)"],
    storageInfo: "Store below 30°C in secure environment.",
    pricePerUnit: 3.50,
    genericAlternative: {
      name: "Alprazolam 0.5 (Jan Aushadhi)",
      genericName: "Alprazolam 0.5mg",
      manufacturer: "PMBJP",
      avgPrice: 0.80,
      savingsPercent: 77,
    },
  },
  {
    id: "med-etizola-05",
    name: "Etizola 0.5",
    genericName: "Etizolam 0.5mg",
    category: "Mental Health",
    form: "Tablet",
    manufacturer: "Macleods Pharmaceuticals",
    prescriptionRequired: true,
    description: "Thienodiazepine derivative with anxiolytic, sedative, muscle relaxant, and anticonvulsant properties.",
    uses: ["Anxiety neurosis", "Sleep onset insomnia associated with anxiety", "Tension headaches"],
    mechanismOfAction: "Potentiates GABAergic inhibition by binding to alpha-1 subunit containing GABA-A receptors in central nervous system.",
    standardDosage: "0.25mg to 0.5mg twice daily or at bedtime.",
    sideEffects: ["Drowsiness", "Muscle weakness", "Headache", "Lightheadedness"],
    precautions: ["Controlled substance — risk of addiction with long-term use", "Avoid operating heavy machinery or driving"],
    storageInfo: "Store below 25°C away from humidity.",
    pricePerUnit: 6.20,
    genericAlternative: {
      name: "Etizolam 0.5 Generic",
      genericName: "Etizolam 0.5mg",
      manufacturer: "PMBJP",
      avgPrice: 1.80,
      savingsPercent: 71,
    },
  },
  {
    id: "med-betnovate-c",
    name: "Betnovate-C Cream",
    genericName: "Betamethasone Valerate (0.1%) + Clioquinol (3%)",
    category: "Dermatology",
    form: "Topical Cream",
    manufacturer: "GSK Pharmaceuticals",
    prescriptionRequired: true,
    description: "Combination of a potent topical corticosteroid and an antibacterial/antifungal agent for inflammatory skin conditions.",
    uses: ["Eczema with secondary infection", "Psoriasis plaques", "Infected contact dermatitis", "Severe skin inflammation"],
    mechanismOfAction: "Betamethasone suppresses skin inflammatory cytokines; Clioquinol exerts antimicrobial action against bacteria and fungi.",
    standardDosage: "Apply a thin film sparingly to affected skin areas 2 to 3 times daily.",
    sideEffects: ["Skin thinning (atrophy) with prolonged use", "Burning sensation", "Striae (stretch marks)", "Hypopigmentation"],
    precautions: ["Do not apply on facial skin for extended periods", "Avoid open wounds or large skin surface areas"],
    storageInfo: "Store below 25°C. Do not freeze.",
    pricePerUnit: 58.00,
    genericAlternative: {
      name: "Betamethasone + Clioquinol Cream (Jan Aushadhi)",
      genericName: "Betamethasone + Clioquinol",
      manufacturer: "PMBJP",
      avgPrice: 18.00,
      savingsPercent: 69,
    },
  },
  {
    id: "med-quadriderm",
    name: "Quadriderm RF Cream",
    genericName: "Beclomethasone + Neomycin + Clotrimazole",
    category: "Dermatology",
    form: "Topical Cream",
    manufacturer: "Fulford India / MSD",
    prescriptionRequired: true,
    description: "Broad-spectrum topical cream formulation tackling mixed skin infections combining corticosteroid, antibiotic, and antifungal.",
    uses: ["Fungal ringworm with inflammation", "Intertrigo & jock itch", "Bacterial-fungal co-infected dermatitis"],
    mechanismOfAction: "Clotrimazole disrupts fungal cell walls; Neomycin stops bacterial protein synthesis; Beclomethasone reduces swelling and itching.",
    standardDosage: "Apply gently to clean, dry affected area twice daily for 7 to 14 days.",
    sideEffects: ["Local skin irritation", "Dry skin", "Redness", "Folliculitis"],
    precautions: ["Do not use continuously for >2 weeks without dermatological re-evaluation", "Keep away from eyes"],
    storageInfo: "Store below 30°C.",
    pricePerUnit: 95.00,
    genericAlternative: {
      name: "Beclomethasone + Neomycin + Clotrimazole (Jan Aushadhi)",
      genericName: "Triple Action Skin Cream",
      manufacturer: "PMBJP",
      avgPrice: 28.00,
      savingsPercent: 71,
    },
  },
  {
    id: "med-panderm-plus",
    name: "Panderm Plus Cream",
    genericName: "Clobetasol Propionate + Neomycin + Miconazole",
    category: "Dermatology",
    form: "Topical Ointment",
    manufacturer: "Macleods Pharmaceuticals",
    prescriptionRequired: true,
    description: "Super-high potency topical steroid combination used for refractory, severe inflammatory fungal skin conditions.",
    uses: ["Severe eczema flare-ups", "Refractory skin fungal infections", "Lichen planus"],
    mechanismOfAction: "Clobetasol offers ultra-potent anti-inflammatory relief while Miconazole/Neomycin eradicate microbial pathogens.",
    standardDosage: "Apply sparingly once or twice daily to affected area for maximum 1 week.",
    sideEffects: ["Skin atrophy", "Telangiectasia (visible blood vessels)", "Steroid acne"],
    precautions: ["Never use on face, groin, or armpits unless specifically prescribed", "Contraindicated in viral skin lesions like chickenpox"],
    storageInfo: "Store below 25°C in a dry place.",
    pricePerUnit: 82.00,
    genericAlternative: {
      name: "Clobetasol + Neomycin Cream (Jan Aushadhi)",
      genericName: "Clobetasol Combination Cream",
      manufacturer: "PMBJP",
      avgPrice: 24.00,
      savingsPercent: 71,
    },
  },
  {
    id: "med-shelcal-500",
    name: "Shelcal 500",
    genericName: "Elemental Calcium (500mg) + Vitamin D3 (250 IU)",
    category: "Vitamin",
    form: "Tablet",
    manufacturer: "Torrent Pharmaceuticals",
    prescriptionRequired: false,
    description: "Essential mineral and vitamin supplement designed to maintain bone mineral density and prevent calcium deficiency.",
    uses: ["Osteoporosis management & prevention", "Osteomalacia & rickets", "Post-menopausal bone weakness", "Calcium deficiency in pregnancy/lactation"],
    mechanismOfAction: "Calcium provides structural structural matrix for bone mineralization; Vitamin D3 enhances intestinal calcium absorption.",
    standardDosage: "1 tablet once or twice daily after meals with water.",
    sideEffects: ["Constipation", "Flatulence", "Nausea", "Hypercalcemia (with excessive overdose)"],
    precautions: ["Caution in patients with history of kidney stones (nephrolithiasis)", "Avoid taking within 2 hours of iron supplements"],
    storageInfo: "Store below 30°C protected from light.",
    pricePerUnit: 8.50,
    genericAlternative: {
      name: "Calcium + Vitamin D3 (Jan Aushadhi)",
      genericName: "Calcium 500mg + Vit D3",
      manufacturer: "PMBJP",
      avgPrice: 2.20,
      savingsPercent: 74,
    },
  },
  {
    id: "med-neurobion-forte",
    name: "Neurobion Forte",
    genericName: "Vitamin B-Complex + Vitamin B12 (Cyanocobalamin)",
    category: "Vitamin",
    form: "Tablet",
    manufacturer: "Procter & Gamble Health",
    prescriptionRequired: false,
    description: "Comprehensive Vitamin B formulation that supports healthy nerve cell function, red blood cell production, and metabolic energy.",
    uses: ["Diabetic neuropathy & nerve pain", "Peripheral tingling & numbness", "Vitamin B deficiency", "General fatigue & anemia recovery"],
    mechanismOfAction: "Essential coenzymes involved in myelin sheath repair, neuronal carbohydrate metabolism, and DNA synthesis.",
    standardDosage: "1 tablet daily after food.",
    sideEffects: ["Mild diarrhea", "Bright yellow discoloration of urine (harmless Riboflavin excretion)", "Nausea"],
    precautions: ["Not a substitute for balanced nutritional diet", "Consult doctor if tingling symptoms worsen"],
    storageInfo: "Store in a cool, dry place below 25°C.",
    pricePerUnit: 2.20,
    genericAlternative: {
      name: "B-Complex + B12 (Jan Aushadhi)",
      genericName: "Vitamin B-Complex Tablets",
      manufacturer: "PMBJP",
      avgPrice: 0.60,
      savingsPercent: 73,
    },
  },
  {
    id: "med-limcee-500",
    name: "Limcee 500",
    genericName: "Vitamin C / Ascorbic Acid 500mg",
    category: "Vitamin",
    form: "Chewable Tablet",
    manufacturer: "Abbott Healthcare",
    prescriptionRequired: false,
    description: "Orange-flavored chewable Vitamin C supplement providing potent antioxidant support, immunity boost, and tissue repair.",
    uses: ["Immune system fortification", "Scurvy treatment & prevention", "Wound healing support", "Iron absorption enhancement"],
    mechanismOfAction: "Acts as an electron donor in metabolic reactions, scavenges free radicals, and synthesizes collagen tissue.",
    standardDosage: "1 to 2 chewable tablets daily after meals.",
    sideEffects: ["Mild gastric acidity", "Heartburn", "Frequent urination (high doses)"],
    precautions: ["Excessive mega-doses (>2000mg/day) may cause oxalate kidney stones", "Chew completely before swallowing"],
    storageInfo: "Store in tight, light-resistant containers below 25°C.",
    pricePerUnit: 1.50,
    genericAlternative: {
      name: "Vitamin C 500 Chewable (Jan Aushadhi)",
      genericName: "Ascorbic Acid 500mg",
      manufacturer: "PMBJP",
      avgPrice: 0.40,
      savingsPercent: 73,
    },
  },
  {
    id: "med-evion-400",
    name: "Evion 400",
    genericName: "Vitamin E / Tocopheryl Acetate 400mg",
    category: "Vitamin",
    form: "Softgel Capsule",
    manufacturer: "Procter & Gamble Health",
    prescriptionRequired: false,
    description: "Fat-soluble antioxidant vitamin capsule supporting skin health, cell membrane protection, muscle cramps, and hair vitality.",
    uses: ["Vitamin E deficiency", "Nocturnal leg cramps", "Non-alcoholic fatty liver support", "Antioxidant cellular protection"],
    mechanismOfAction: "Protects cell membranes from lipid peroxidation caused by free radicals and oxidative degradation.",
    standardDosage: "1 softgel capsule daily after a meal containing healthy fats.",
    sideEffects: ["Nausea", "Fatigue", "Mild headache", "Blurred vision (rare high dose)"],
    precautions: ["High doses may increase bleeding risk if taken with blood thinners like Warfarin or Aspirin"],
    storageInfo: "Store below 30°C away from heat and direct sunlight.",
    pricePerUnit: 3.80,
    genericAlternative: {
      name: "Vitamin E 400 Softgel (Jan Aushadhi)",
      genericName: "Vitamin E 400mg",
      manufacturer: "PMBJP",
      avgPrice: 1.10,
      savingsPercent: 71,
    },
  },
  {
    id: "med-d3-must-60k",
    name: "Tayo 60K / D3 Must",
    genericName: "Cholecalciferol / Vitamin D3 60,000 IU",
    category: "Vitamin",
    form: "Softgel Capsule / Granules",
    manufacturer: "Mankind Pharma",
    prescriptionRequired: true,
    description: "High-potency therapeutic weekly dose of Vitamin D3 designed to rapidly correct clinical Vitamin D deficiency.",
    uses: ["Severe Vitamin D deficiency", "Osteoporosis treatment adjunct", "Bone pain & muscle fatigue", "Hypocalcemia management"],
    mechanismOfAction: "Converted in liver and kidney to active Calcitriol, which increases intestinal absorption of calcium and phosphate.",
    standardDosage: "1 capsule (60,000 IU) ONCE WEEKLY for 6 to 8 weeks, followed by monthly maintenance or as prescribed.",
    sideEffects: ["Hypercalcemia (if overused)", "Nausea & vomiting", "Weakness", "Dry mouth"],
    precautions: ["Do NOT take daily — this is a high-dose weekly formulation", "Monitor serum 25-hydroxy vitamin D levels"],
    storageInfo: "Store in a cool dry place below 25°C.",
    pricePerUnit: 32.00,
    genericAlternative: {
      name: "Vitamin D3 60K (Jan Aushadhi)",
      genericName: "Cholecalciferol 60,000 IU",
      manufacturer: "PMBJP",
      avgPrice: 8.50,
      savingsPercent: 73,
    },
  },
  {
    id: "med-betadine-ointment",
    name: "Betadine 10% Ointment",
    genericName: "Povidone-Iodine 10% w/w",
    category: "First-Aid",
    form: "Topical Antiseptic Ointment",
    manufacturer: "Win-Medicare Pvt Ltd",
    prescriptionRequired: false,
    description: "Gold-standard broad-spectrum topical microbicidal antiseptic active against bacteria, viruses, fungi, and spores.",
    uses: ["Minor cuts, scrapes & burns", "Surgical wound dressing", "Prevention of infection in abrasions", "Ulcer bed treatment"],
    mechanismOfAction: "Slowly releases free iodine which oxidizes microbial proteins, amino acids, and nucleic acids, killing pathogens.",
    standardDosage: "Clean affected area and apply thin layer 1 to 3 times daily; cover with sterile bandage if needed.",
    sideEffects: ["Local skin irritation or redness", "Staining of skin and clothes (reversible)", "Transient burning"],
    precautions: ["Avoid applying over massive burn areas (risk of systemic iodine absorption)", "Caution in thyroid disorders"],
    storageInfo: "Store below 25°C in tightly closed tube.",
    pricePerUnit: 125.00,
    genericAlternative: {
      name: "Povidone Iodine 10% Ointment (Jan Aushadhi)",
      genericName: "Povidone-Iodine Ointment",
      manufacturer: "PMBJP",
      avgPrice: 42.00,
      savingsPercent: 66,
    },
  },
  {
    id: "med-volini-gel",
    name: "Volini Pain Relief Gel",
    genericName: "Diclofenac Diethylamine + Linseed Oil + Methyl Salicylate + Menthol",
    category: "First-Aid",
    form: "Topical Gel",
    manufacturer: "Sun Pharmaceutical Industries",
    prescriptionRequired: false,
    description: "Fast-absorbing topical analgesic gel offering targeted relief from deep-seated muscular aches, backaches, and sprains.",
    uses: ["Lower back pain", "Sports injuries & sprains", "Joint pain & stiffness", "Neck & shoulder muscular strain"],
    mechanismOfAction: "Diclofenac penetrates skin to block COX enzymes; Menthol creates cooling sensation; Methyl Salicylate acts as rubefacient.",
    standardDosage: "Gently rub 2 to 4 grams of gel over affected painful region 3 to 4 times daily.",
    sideEffects: ["Mild local skin redness", "Itching", "Dry skin at site of application"],
    precautions: ["Do not apply to open wounds, cut skin, or eyes", "Wash hands thoroughly after application"],
    storageInfo: "Store below 30°C. Keep tube tightly closed.",
    pricePerUnit: 140.00,
    genericAlternative: {
      name: "Diclofenac Pain Relief Gel (Jan Aushadhi)",
      genericName: "Diclofenac Gel Formula",
      manufacturer: "PMBJP",
      avgPrice: 38.00,
      savingsPercent: 73,
    },
  },
  {
    id: "med-ors-electral",
    name: "Electral Powder ORS",
    genericName: "Oral Rehydration Salts (WHO Formula)",
    category: "First-Aid",
    form: "Sachet Powder",
    manufacturer: "FDC Ltd",
    prescriptionRequired: false,
    description: "WHO-recommended oral rehydration formulation containing precise ratio of electrolytes and glucose for rapid fluid recovery.",
    uses: ["Diarrhea & vomiting dehydration", "Heat exhaustion & heavy sweating", "Post-exercise fluid replacement", "Fever-induced fluid loss"],
    mechanismOfAction: "Glucose enhances active sodium transport across intestinal mucosa, driving rapid water absorption into bloodstream.",
    standardDosage: "Dissolve entire 21.8g sachet contents in EXACTLY 1 Liter of clean drinking water. Drink frequently as required.",
    sideEffects: ["Vomiting (if consumed too rapidly)", "Hypernatremia (if mixed with too little water)"],
    precautions: ["Do NOT boil the solution after mixing", "Discard any unused reconstituted solution after 24 hours"],
    storageInfo: "Store sachets in dry place away from moisture.",
    pricePerUnit: 22.00,
    genericAlternative: {
      name: "ORS Sachet (Jan Aushadhi)",
      genericName: "Oral Rehydration Salts WHO",
      manufacturer: "PMBJP",
      avgPrice: 9.00,
      savingsPercent: 59,
    },
  },
  {
    id: "med-drotin-m",
    name: "Drotin-M",
    genericName: "Drotaverine HCl (80mg) + Mefenamic Acid (250mg)",
    category: "Women Health",
    form: "Tablet",
    manufacturer: "Walter Bushnell",
    prescriptionRequired: true,
    description: "Potent smooth muscle antispasmodic and analgesic specifically tailored for severe gynecological and abdominal spasms.",
    uses: ["Severe dysmenorrhea (menstrual painful cramps)", "Uterine spasms", "Renal colic & gallstone pain"],
    mechanismOfAction: "Drotaverine inhibits PDE-4 enzyme in smooth muscle to relieve spasm; Mefenamic acid inhibits pain-inducing prostaglandins.",
    standardDosage: "1 tablet 2 to 3 times daily after food during heavy pain days.",
    sideEffects: ["Nausea & dizziness", "Dry mouth", "Vertigo", "Heartburn"],
    precautions: ["Caution in severe renal or hepatic impairment", "Avoid taking on an empty stomach"],
    storageInfo: "Store below 25°C away from moisture.",
    pricePerUnit: 14.50,
    genericAlternative: {
      name: "Drotaverine + Mefenamic (Jan Aushadhi)",
      genericName: "Drotaverine 80mg + Mefenamic 250mg",
      manufacturer: "PMBJP",
      avgPrice: 4.20,
      savingsPercent: 71,
    },
  },
  {
    id: "med-duphaston-10",
    name: "Duphaston 10",
    genericName: "Dydrogesterone 10mg",
    category: "Women Health",
    form: "Film-coated Tablet",
    manufacturer: "Abbott Healthcare",
    prescriptionRequired: true,
    description: "Orally active progestogen chemically closely related to natural progesterone, used in diverse gynecological conditions.",
    uses: ["Threatened or recurrent miscarriage support", "Endometriosis management", "Irregular menstrual cycles", "Infertility due to luteal insufficiency"],
    mechanismOfAction: "Selectively acts on uterine endometrium to promote normal secretory transformation without androgenic side effects.",
    standardDosage: "1 tablet (10mg) 1 to 2 times daily as specific calendar regimen defined by gynecologist.",
    sideEffects: ["Headache & migraine", "Nausea", "Breast tenderness", "Metrorrhagia (spotting)"],
    precautions: ["Regular clinical assessment required for long-term hormonal therapy", "Contraindicated in undiagnosed vaginal bleeding"],
    storageInfo: "Store below 30°C in dark dry place.",
    pricePerUnit: 72.00,
    genericAlternative: {
      name: "Dydrogesterone 10 (Jan Aushadhi)",
      genericName: "Dydrogesterone 10mg",
      manufacturer: "PMBJP / Mankind",
      avgPrice: 22.00,
      savingsPercent: 69,
    },
  },
  {
    id: "med-i-pill",
    name: "i-Pill",
    genericName: "Levonorgestrel 1.5mg",
    category: "Women Health",
    form: "Tablet",
    manufacturer: "Piramal Pharma",
    prescriptionRequired: false,
    description: "Emergency contraceptive pill designed to prevent unintended pregnancy when taken within 72 hours of unprotected intercourse.",
    uses: ["Emergency contraception post unprotected intercourse", "Contraceptive failure (condom breakage)"],
    mechanismOfAction: "Primarily prevents ovulation or fertilization by delaying egg release from ovaries; does NOT terminate an existing pregnancy.",
    standardDosage: "Single 1.5mg tablet swallowed with water as soon as possible, ideally within 24–72 hours.",
    sideEffects: ["Nausea & lower abdominal pain", "Fatigue", "Headache", "Temporary menstrual cycle irregularity"],
    precautions: ["NOT an abortion pill and ineffective once implantation has occurred", "Should not be used as a routine regular contraceptive method"],
    storageInfo: "Store below 25°C in original packaging.",
    pricePerUnit: 110.00,
    genericAlternative: {
      name: "Levonorgestrel 1.5 Emergency (Jan Aushadhi)",
      genericName: "Levonorgestrel 1.5mg",
      manufacturer: "PMBJP",
      avgPrice: 32.00,
      savingsPercent: 71,
    },
  },
  {
    id: "med-primolut-n",
    name: "Primolut-N",
    genericName: "Norethisterone 5mg",
    category: "Women Health",
    form: "Tablet",
    manufacturer: "Bayer Pharmaceuticals",
    prescriptionRequired: true,
    description: "Potent synthetic progestin tablet prescribed to delay periods, treat heavy menstrual bleeding, or manage endometriosis.",
    uses: ["Menstrual postponement", "Dysfunctional uterine bleeding (DUB)", "Endometriosis", "Severe dysmenorrhea"],
    mechanismOfAction: "Transforms proliferative endometrium into secretory state and inhibits pituitary gonadotropin secretion to suspend bleeding.",
    standardDosage: "1 tablet (5mg) 2 to 3 times daily starting 3 days before expected period date to delay menses.",
    sideEffects: ["Spotting / breakthrough bleeding", "Nausea", "Headache", "Fluid retention / bloating"],
    precautions: ["Contraindicated in high thromboembolism (blood clot) risk or active liver disease", "Not a primary contraceptive"],
    storageInfo: "Store below 30°C.",
    pricePerUnit: 6.80,
    genericAlternative: {
      name: "Norethisterone 5 (Jan Aushadhi)",
      genericName: "Norethisterone 5mg",
      manufacturer: "PMBJP",
      avgPrice: 1.80,
      savingsPercent: 74,
    },
  },
  {
    id: "med-autrin-capsule",
    name: "Autrin Capsule",
    genericName: "Ferrous Fumarate + Folic Acid + Vitamin B12",
    category: "Women Health",
    form: "Capsule",
    manufacturer: "Pfizer Ltd",
    prescriptionRequired: false,
    description: "Comprehensive hematinic blood-builder capsule formulated to treat and prevent iron-deficiency anemia.",
    uses: ["Iron deficiency anemia", "Pregnancy & lactation nutritional support", "Heavy menstrual blood loss recovery", "Nutritional weakness"],
    mechanismOfAction: "Ferrous fumarate replenishes elemental iron stores for hemoglobin synthesis; Folic acid and B12 drive red blood cell maturation.",
    standardDosage: "1 capsule daily after main meal.",
    sideEffects: ["Dark/black colored stools (harmless)", "Constipation or mild diarrhea", "Nausea & epigastric distress"],
    precautions: ["Do not take simultaneously with tea, coffee, or milk (inhibits iron absorption)", "Keep out of reach of children"],
    storageInfo: "Store in cool dry place away from direct light.",
    pricePerUnit: 6.50,
    genericAlternative: {
      name: "Ferrous Fumarate + Folic Acid (Jan Aushadhi)",
      genericName: "Iron & Folic Acid Capsule",
      manufacturer: "PMBJP",
      avgPrice: 1.60,
      savingsPercent: 75,
    },
  },
  {
    id: "med-deriphyllin-retard",
    name: "Deriphyllin Retard 150",
    genericName: "Etofylline (115mg) + Theophylline (35mg)",
    category: "Respiratory",
    form: "Sustained Release Tablet",
    manufacturer: "Zydus Healthcare",
    prescriptionRequired: true,
    description: "Xanthine derivative bronchodilator for long-term airway management in chronic obstructive pulmonary diseases.",
    uses: ["Bronchial asthma maintenance", "Chronic obstructive pulmonary disease (COPD)", "Chronic bronchitis wheezing"],
    mechanismOfAction: "Relaxes smooth muscles of respiratory bronchial passages and pulmonary blood vessels by inhibiting phosphodiesterase enzymes.",
    standardDosage: "1 tablet twice daily (every 12 hours) after food.",
    sideEffects: ["Nausea & gastric irritation", "Insomnia & restlessness", "Headache", "Tachycardia / palpitations"],
    precautions: ["Caution in patients with peptic ulcers or cardiac arrhythmias", "Do not crush or chew sustained-release tablet"],
    storageInfo: "Store below 25°C in moisture-resistant strip.",
    pricePerUnit: 3.20,
    genericAlternative: {
      name: "Etofylline + Theophylline SR (Jan Aushadhi)",
      genericName: "Etofylline + Theophylline 150mg SR",
      manufacturer: "PMBJP",
      avgPrice: 0.90,
      savingsPercent: 72,
    },
  },
  {
    id: "med-solvin-cold",
    name: "Solvin Cold Tablet",
    genericName: "Paracetamol (325mg) + Phenylephrine (5mg) + Chlorpheniramine (2mg)",
    category: "Respiratory",
    form: "Tablet",
    manufacturer: "Ipca Laboratories",
    prescriptionRequired: false,
    description: "Multi-symptom cold and flu relief combination addressing nasal blockage, fever, headache, and runny nose.",
    uses: ["Common cold & flu symptoms", "Nasal congestion & blocked sinus", "Allergic rhinitis with fever", "Sneezing & watery eyes"],
    mechanismOfAction: "Phenylephrine constricts nasal blood vessels; Chlorpheniramine blocks histamine; Paracetamol lowers fever and body pain.",
    standardDosage: "1 tablet 3 times daily after food.",
    sideEffects: ["Drowsiness & sedation", "Dry mouth", "Mild blood pressure elevation", "Dizziness"],
    precautions: ["Caution in uncontrolled high blood pressure or glaucoma", "May cause sedation — avoid driving"],
    storageInfo: "Store below 30°C.",
    pricePerUnit: 5.50,
    genericAlternative: {
      name: "Cold & Fever Relief Tablet (Jan Aushadhi)",
      genericName: "Paracetamol + Phenylephrine + CPM",
      manufacturer: "PMBJP",
      avgPrice: 1.40,
      savingsPercent: 75,
    },
  },
  {
    id: "med-cidmus-50",
    name: "Cidmus 50",
    genericName: "Sacubitril (24mg) + Valsartan (26mg)",
    category: "Cardiac",
    form: "Film-coated Tablet",
    manufacturer: "Lupin Ltd / Novartis",
    prescriptionRequired: true,
    description: "Angiotensin Receptor-Neprilysin Inhibitor (ARNI) revolutionary cardiac therapy that reduces hospitalization risk in heart failure.",
    uses: ["Heart Failure with Reduced Ejection Fraction (HFrEF)", "Cardiovascular death risk reduction"],
    mechanismOfAction: "Sacubitril inhibits neprilysin enzyme boosting beneficial natriuretic peptides; Valsartan blocks harmful angiotensin II receptors.",
    standardDosage: "1 tablet twice daily, titrated upwards as tolerated under strict cardiologist supervision.",
    sideEffects: ["Hypotension (low BP)", "Hyperkalemia", "Renal impairment", "Angioedema (rare)"],
    precautions: ["Do NOT take with ACE inhibitors (must allow 36-hour wash-out period)", "Contraindicated in pregnancy"],
    storageInfo: "Store below 30°C protected from moisture.",
    pricePerUnit: 45.00,
    genericAlternative: {
      name: "Sacubitril + Valsartan 50 (Jan Aushadhi)",
      genericName: "Sacubitril + Valsartan 50mg",
      manufacturer: "PMBJP",
      avgPrice: 14.00,
      savingsPercent: 69,
    },
  },
  {
    id: "med-liv-52",
    name: "Liv.52 Tablet",
    genericName: "Herbal Extract Blend (Caper Bush, Chicory, Arjuna)",
    category: "General",
    form: "Phytopharmaceutical Tablet",
    manufacturer: "Himalaya Wellness Company",
    prescriptionRequired: false,
    description: "Widely trusted phytopharmaceutical liver care formula that protects liver parenchyma and promotes hepatic regeneration.",
    uses: ["Alcoholic liver disease support", "Early cirrhosis protection", "Loss of appetite & sluggish digestion", "Drug-induced hepatotoxicity protection"],
    mechanismOfAction: "Restores functional efficiency of liver cells, protects cytochrome P-450 enzymes, and speeds up recovery from jaundice.",
    standardDosage: "2 tablets twice daily before meals.",
    sideEffects: ["Virtually no major side effects reported when taken as recommended"],
    precautions: ["Should not replace primary medical treatment for severe liver conditions like viral Hepatitis B/C"],
    storageInfo: "Store in a dry place away from direct sunlight.",
    pricePerUnit: 2.20,
    genericAlternative: {
      name: "Herbal Liver Care (Jan Aushadhi)",
      genericName: "Herbal Hepato-Protective Tablet",
      manufacturer: "PMBJP / Ayush",
      avgPrice: 0.90,
      savingsPercent: 59,
    },
  },
  {
    id: "med-revital-h",
    name: "Revital H Daily Health",
    genericName: "Ginseng Extract + Multivitamins + Minerals",
    category: "General",
    form: "Softgel Capsule",
    manufacturer: "Sun Pharmaceutical Industries",
    prescriptionRequired: false,
    description: "Daily health and energy supplement combining natural Ginseng extract with 10 vitamins and 9 minerals to combat fatigue.",
    uses: ["Daily energy & stamina enhancement", "Mental alertness & focus", "Immunity support", "Nutritional deficiency fill"],
    mechanismOfAction: "Ginseng adaptogen improves oxygen utilization in tissues; Vitamins/minerals support metabolic ATP synthesis.",
    standardDosage: "1 capsule daily with morning breakfast or milk.",
    sideEffects: ["Mild insomnia (if taken late at night)", "Mild stomach upset"],
    precautions: ["Take a 2-week break after continuous daily use for 3 months", "Not recommended for children"],
    storageInfo: "Store below 25°C in a dry place.",
    pricePerUnit: 11.00,
    genericAlternative: {
      name: "Ginseng + Multivitamin Softgel (Jan Aushadhi)",
      genericName: "Multivitamin with Ginseng",
      manufacturer: "PMBJP",
      avgPrice: 3.20,
      savingsPercent: 71,
    },
  },
  {
    id: "med-cyclopam",
    name: "Cyclopam",
    genericName: "Dicyclomine HCl (20mg) + Paracetamol (500mg)",
    category: "General",
    form: "Tablet",
    manufacturer: "Indoco Remedies",
    prescriptionRequired: true,
    description: "Antispasmodic and analgesic combination for quick relief from acute stomach cramps, intestinal colic, and bloating pain.",
    uses: ["Intestinal spasmodic cramps", "Irritable Bowel Syndrome (IBS) pain", "Biliary colic", "Abdominal pain with fever"],
    mechanismOfAction: "Dicyclomine directly relaxes smooth muscles of GI tract wall; Paracetamol blocks central pain signaling.",
    standardDosage: "1 tablet 2 to 3 times daily after food as required.",
    sideEffects: ["Dry mouth", "Dizziness & drowsiness", "Blurred vision", "Constipation"],
    precautions: ["Caution in prostatic hypertrophy and narrow-angle glaucoma", "Avoid driving post-consumption"],
    storageInfo: "Store below 30°C.",
    pricePerUnit: 4.80,
    genericAlternative: {
      name: "Dicyclomine + Paracetamol (Jan Aushadhi)",
      genericName: "Dicyclomine 20mg + Paracetamol 500mg",
      manufacturer: "PMBJP",
      avgPrice: 1.30,
      savingsPercent: 73,
    },
  },
  {
    id: "med-silodosin-8",
    name: "Silofast 8 / Silodosin",
    genericName: "Silodosin 8mg",
    category: "General",
    form: "Capsule",
    manufacturer: "Cipla Ltd",
    prescriptionRequired: true,
    description: "Highly selective alpha-1A adrenergic receptor antagonist used to improve urinary outflow in Benign Prostatic Hyperplasia (BPH).",
    uses: ["Benign Prostatic Hyperplasia (BPH) symptoms", "Hesitancy & weak urinary stream", "Frequent nighttime urination (Nocturia)"],
    mechanismOfAction: "Selectively blocks alpha-1A adrenoreceptors in prostate, bladder neck, and prostatic urethra, relaxing smooth muscle.",
    standardDosage: "1 capsule (8mg) once daily with a meal (preferably dinner).",
    sideEffects: ["Retrograde ejaculation (harmless backflow of semen)", "Dizziness", "Nasal congestion", "Orthostatic hypotension"],
    precautions: ["Inform eye surgeon prior to cataract surgery (risk of Intraoperative Floppy Iris Syndrome)", "Take with meals for optimal absorption"],
    storageInfo: "Store below 25°C protected from light.",
    pricePerUnit: 34.00,
    genericAlternative: {
      name: "Silodosin 8 (Jan Aushadhi)",
      genericName: "Silodosin 8mg",
      manufacturer: "PMBJP",
      avgPrice: 9.50,
      savingsPercent: 72,
    },
  },
  {
    id: "med-tab-thyronorm-50",
    name: "Thyronorm 50",
    genericName: "Levothyroxine Sodium 50mcg",
    category: "General",
    form: "Tablet",
    manufacturer: "Abbott India",
    prescriptionRequired: true,
    description: "Synthetic thyroid hormone replacement therapy used to restore thyroid hormone levels in hypothyroid conditions.",
    uses: ["Hypothyroidism (underactive thyroid)", "Goiter management", "Post-thyroidectomy hormone replacement"],
    mechanismOfAction: "Synthetic T4 hormone converts to active T3 in peripheral tissues, regulating basal metabolic rate, energy, and protein synthesis.",
    standardDosage: "1 tablet daily in the morning strictly on AN EMPTY STOMACH with water, 30-60 mins before breakfast.",
    sideEffects: ["Hyperthyroidism symptoms (if overdosed): palpitations, weight loss, tremors, heat intolerance"],
    precautions: ["Do NOT take with calcium, iron, or antacid supplements within 4 hours", "Requires periodic TSH blood tests to fine-tune dosage"],
    storageInfo: "Store between 15°C–25°C in original bottle tightly capped.",
    pricePerUnit: 2.10,
    genericAlternative: {
      name: "Levothyroxine 50 (Jan Aushadhi)",
      genericName: "Levothyroxine Sodium 50mcg",
      manufacturer: "PMBJP",
      avgPrice: 0.55,
      savingsPercent: 74,
    },
  },
];

export function getDetailedMedicineByName(search: string): DetailedMedicine | null {
  if (!search || !search.trim()) return DETAILED_MEDICINES[0];
  const q = search.toLowerCase().trim();
  const match = DETAILED_MEDICINES.find(
    (m) =>
      m.name.toLowerCase().includes(q) ||
      m.genericName.toLowerCase().includes(q) ||
      m.category.toLowerCase().includes(q)
  );
  return match || null;
}